// Approved static pre-login lessons. No client state or assessment conclusions.
export const loginTopics = {
grc:['Three parts. One stronger program.','Governance sets direction and ownership. Risk management helps you decide what could go wrong and what to do about it. Compliance checks requirements and the evidence behind them. Together, they turn security into an ongoing business practice. For example: governance assigns an access-review owner; risk helps prioritize sensitive access; compliance checks the required review and its evidence.'],
governance:['Who owns the decisions?','Governance gives your program direction: clear policies, named owners, leadership decisions, and regular oversight. It helps everyone understand what is expected and who is accountable.'],
risk:['Focus on what matters most.','Risk management looks at what could go wrong, how likely it is, and how much it could affect the business. Then you choose a response, assign an owner, and track whether that response is working.'],
compliance:['Show how you meet requirements.','Compliance means understanding applicable obligations, putting the right practices in place, and keeping evidence. That can include contractual commitments, laws, and standards. It supports confidence—but does not mean every risk is gone.'],
cis:['A practical path through security.','CIS Implementation Groups help prioritize safeguards. IG1 is essential cyber hygiene: 56 safeguards. IG2 builds on it with 74 more, for 130 total. IG3 adds 23 more, covering all 153. Choose based on risk, complexity, and resources—not just a desire for a higher number.','https://www.cisecurity.org/controls/implementation-groups'],
iso:['Build a system for managing security.','ISO/IEC 27001 sets requirements for an information security management system, or ISMS. It connects risks, responsibilities, controls, reviews, and continual improvement. It helps make security a repeatable management practice. Certification requires an independent assessment.','https://www.iso.org/standard/27001'],
soc:['Give customers independent assurance.','SOC 2 is an independent CPA examination of a service organization’s controls against relevant Trust Services Criteria. Its scope can address security, availability, processing integrity, confidentiality, and privacy. It helps customers evaluate how a provider protects the services and information they rely on.','https://www.aicpa-cima.com/resources/landing/system-and-organization-controls-soc-suite-of-services']};
export const loginLessons = {
governance:{name:'Governance',questions:[
['What is governance?','Set direction. Make ownership clear.','Governance is how an organization directs and oversees its security program. It defines expectations, decision-making authority, accountability, and how leadership checks progress.','Leadership approves an access policy, assigns an owner, and reviews whether access reviews happen.'],
['Why is it important?','Turn good intentions into decisions.','Without governance, important work can fall between teams. Clear ownership, priorities, and oversight help security decisions support business goals and ensure unresolved issues reach the right people.','A recurring backup issue reaches a leader who can approve the resources to fix it.'],
['Who is responsible?','Leadership oversees. Owners deliver.','The governing body and senior leadership provide direction and oversight. Program leaders coordinate the work; business and control owners operate their processes. Employees follow expectations and report concerns. Security is not solely an IT responsibility.','HR owns timely departure notifications; IT removes access; a designated reviewer checks completion.'],
['What does it look like?','Decisions with a follow-through.','Look for approved policies, assigned responsibilities, documented decisions, regular management reviews, and tracked actions. Good governance connects an issue to an owner, a decision, and a follow-up.','A quarterly review records an overdue control, its responsible owner, and an agreed completion date.']
]},
risk:{name:'Risk',questions:[
['What is risk?','Uncertainty with a business impact.','In security, risk concerns the potential for an event to harm information, operations, or business objectives. A useful scenario connects a threat, a weakness or exposure, and the resulting consequence.','A stolen password could let an attacker access customer information.'],
['Why assess it?','Put effort where it matters.','Risk assessment helps compare potential problems, choose priorities, and explain security investments. It considers the business impact and likelihood of a scenario instead of treating every weakness as equally urgent.','An exposed administrator account may need attention before a minor issue on an isolated test device.'],
['How is risk scored?','Likelihood and impact guide the discussion.','A common model combines likelihood and impact, sometimes multiplying defined scores such as 1–5. Those ratings require agreed criteria and judgment; they are not precise probabilities. Other models estimate financial loss or use qualitative categories.','Likelihood 3 × impact 4 gives 12 in one organization’s model. Its own thresholds determine what 12 means.'],
['Inherent vs. residual?','Before controls. After controls.','Inherent risk is assessed before considering controls. Residual risk is what remains after considering controls and their effectiveness. Controls may reduce likelihood, impact, or both; they rarely eliminate all risk.','MFA and access monitoring can reduce account-takeover risk, but some exposure remains.'],
['How do we respond?','Choose a response and an owner.','Common responses are to reduce risk with controls, avoid the risky activity, transfer or share some consequences, or accept the risk through the appropriate authority. Track the response and reassess when circumstances change.','Cyber insurance may transfer some financial consequences; it does not remove responsibility for protecting systems.'],
['Who owns the risk?','The business owns the decision.','A named risk owner is accountable for managing the scenario and escalating decisions. Security specialists advise, control owners carry out actions, and acceptance follows the organization’s approval authority and risk tolerance.','An operations leader owns a service-outage risk; IT implements recovery controls and reports test results.']
]},
compliance:{name:'Compliance',questions:[
['What is compliance?','Meet the obligations that apply.','Compliance means fulfilling applicable requirements. These may come from laws, regulations, contracts, internal policies, or standards the organization has adopted. The first step is deciding what applies to the organization and its scope.','A customer contract requires annual access reviews and a defined incident-notification process.'],
['Why does it matter?','Keep commitments and demonstrate trust.','Meeting applicable requirements supports customer confidence, contractual commitments, and accountability. Missing them can lead to findings, remediation costs, lost business, or legal consequences, depending on the obligation.','A supplier can show a customer evidence that the access reviews promised in its contract were completed.'],
['How do we demonstrate it?','Connect requirements to evidence.','Identify the requirement, assign an owner, operate the relevant control, and retain appropriate evidence. Review whether the evidence shows the control worked across the required scope and period—not simply that a policy exists.','An approved access policy explains the process; completed review records show that reviewers carried it out.'],
['Does compliant mean secure?','Requirements are a baseline, not a guarantee.','Compliance and security support each other, but they are not interchangeable. A defined assessment covers a particular scope and period. Threats, systems, and business needs can change, so risk management and improvement must continue.','An organization can pass an assessment and still need to address a newly discovered vulnerability.']
]}};
export const loginMenu = [['grc', 'What is GRC?'], ['cis', 'CIS IG1, IG2 & IG3'], ['iso', 'What is ISO 27001?'], ['soc', 'What is SOC 2?']];
export function loginGreeting(date = new Date()) {
  const hour = date.getHours();
  return `${hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening'}—I’m Omni.`;
}

