import {cloneElement,useEffect,useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import api,{formatError} from '@/lib/api';
import {useCreateIntent} from '@/lib/createIntent';
import {useAuth} from '@/context/AuthContext';
import {AI_DEFAULTS,AI_KEYS,aiScreening,catalog} from '@/lib/aiGovernance';
import RecordDrawer from './RecordDrawer';
import AssigneeSelect from './AssigneeSelect';
import {SCHEMAS} from '@/lib/schemas';

const IDS={reviews:'review_id',risks:'risk_id',findings:'finding_id',tasks:'task_id',policies:'policy_id',vendors:'vendor_id',requirements:'requirement_id'};
const SELECT='h-9 w-full rounded-md border border-line bg-surface-card px-2 text-sm';
function Field({label,children}){return <label className="block space-y-1 text-sm"><span className="text-ink-secondary">{label}</span>{cloneElement(children,{'aria-label':label})}</label>;}
function Choices({label,values,selected=[],onChange,disabled}){return <fieldset disabled={disabled} className="border border-line rounded-md p-3"><legend className="px-1 text-sm">{label}</legend><div className="grid sm:grid-cols-2 gap-2">{values.map(v=><label key={v} className="flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(v)} onChange={e=>onChange(e.target.checked?[...selected,v]:selected.filter(x=>x!==v))}/>{v}</label>)}</div></fieldset>;}

export default function AIDrawer({open,onOpenChange,record,clientId,users=[],onSaved}){
  const {user}=useAuth(),id=record?.ai_system_id;
  const createRecord=useCreateIntent((...args)=>api.post(...args),clientId);
  const [form,setForm]=useState(()=>({...AI_DEFAULTS,...record})),[tab,setTab]=useState('Overview'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[context,setContext]=useState(null),[nested,setNested]=useState(null);
  const [schedule,setSchedule]=useState({due_date:'',recurrence:'annual',custom_recurrence_days:90}),[change,setChange]=useState(''),[link,setLink]=useState({kind:'risks',id:'',classification:'Context',source:'',rationale:''});
  const admin=['super_admin','platform_admin'].includes(user?.role),writable=['super_admin','platform_admin','client_contributor'].includes(user?.role),historical=(context?.row||record)?.status==='retired',editable=writable&&!historical;
  const current=context?.row||record,screen=aiScreening(form);
  useEffect(()=>{const c=new AbortController();setContext(null);setError('');
    const opts={params:{client_id:clientId},signal:c.signal};
    Promise.all([Promise.all(Object.keys(IDS).filter(k=>k!=='reviews').map(async k=>[k,(await api.get('/'+k,opts)).data])),id?api.get('/related',{params:{entity_type:'ai_systems',entity_id:id},signal:c.signal}):{data:{}},id?api.get(`/ai_systems/${id}/activity`,{signal:c.signal}):{data:[]},id?api.get('/ai_systems',opts):{data:[]}]).then(([options,related,activity,rows])=>{if(!c.signal.aborted)setContext({options:Object.fromEntries(options),related:related.data,activity:activity.data,row:rows.data.find(r=>r.ai_system_id===id)});}).catch(e=>{if(!c.signal.aborted)setError(formatError(e));});return()=>c.abort();
  },[clientId,id,revision]);
  const put=(key,value)=>setForm(p=>({...p,[key]:value}));
  const input=(key,label,multiline=false)=> <Field label={label}>{multiline?<Textarea value={form[key]||''} onChange={e=>put(key,e.target.value)}/>:<Input value={form[key]||''} onChange={e=>put(key,e.target.value)} required={key==='name'}/>}</Field>;
  const person=(key,label)=> <div><span className="text-sm">{label}</span><AssigneeSelect clientId={clientId} label={label} value={form[key]} onChange={v=>put(key,v)} users={users}/></div>;
  const boolean=(label,value,onChange)=><Field label={label}><select className={SELECT} value={value===true?'yes':value===false?'no':''} onChange={e=>onChange(e.target.value===''?null:e.target.value==='yes')}><option value="">Not assessed</option><option value="yes">Yes</option><option value="no">No</option></select></Field>;
  async function run(fn){setBusy(true);setError('');try{await fn();setRevision(n=>n+1);}catch(e){setError(formatError(e));}finally{setBusy(false);}}
  async function save(e){e.preventDefault();await run(async()=>{const body={client_id:clientId,...Object.fromEntries(AI_KEYS.map(k=>[k,form[k]]))};await (id?api.patch(`/ai_systems/${id}`,{...body,expected_updated_at:form.updated_at??null}):createRecord('/ai_systems',body));onSaved?.();onOpenChange(false);});}
  function openRecord(kind,row){setNested({kind,record:row});}
  async function upload(file){if(!file)return;await run(async()=>{const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});await api.post('/evidence',{client_id:clientId,linked_type:'ai_system',linked_id:id,filename:file.name,mime_type:file.type||'application/octet-stream',content_base64:content});});}
  async function download(ev){await run(async()=>{const {data}=await api.get(`/evidence/${ev.evidence_id}/download`);const a=document.createElement('a');a.href=data.content_base64.startsWith('data:')?data.content_base64:`data:${data.mime_type};base64,${data.content_base64}`;a.download=data.filename;a.click();});}
  const related=context?.related||{};
  function recordList(kind,rows){return <ul className="space-y-2">{rows.map(r=><li key={r[IDS[kind]]} className="border border-line rounded p-3 flex justify-between gap-3 text-sm"><button className="text-link text-left" onClick={()=>openRecord(kind,r)}>{r.display_id?`${r.display_id} · `:''}{r.title||r.name}</button><span className="text-xs text-ink-muted">{r.status?.replaceAll('_',' ')}{kind==='reviews'&&` · ${r.due_date?.slice(0,10)||'Needs scheduling'}`}</span></li>)}</ul>;}
  const tabs=id?['Overview','Risk & Governance','Reviews','Related','Evidence','Activity']:['Overview','Risk & Governance'];
  return <><Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full sm:max-w-3xl overflow-y-auto bg-surface-card" data-testid="ai-drawer"><SheetHeader><SheetTitle>{record?`${record.display_id} · ${record.name}`:'Add AI System / Use Case'}</SheetTitle><SheetDescription>Governed context, not a separate risk or remediation register.</SheetDescription></SheetHeader><div className="flex gap-2 overflow-x-auto border-b border-line mt-4 mb-5" role="tablist" aria-label="AI record sections">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} className={`drawer-tab whitespace-nowrap ${tab===t?'active':''}`}>{t}</button>)}</div>{error&&<p role="alert" className="text-sm text-semantic-critical mb-3">{error}</p>}
    {historical&&<p className="text-sm text-ink-muted mb-4">Retired · Record and governance history retained. Started closure work may still finish without recurrence.</p>}
    {['Overview','Risk & Governance'].includes(tab)&&<form onSubmit={save} className="space-y-4"><fieldset disabled={!editable||busy} className="space-y-4">
      {tab==='Overview'?<><div className="grid sm:grid-cols-2 gap-4">{input('name','AI System / Use Case name')}{input('product_model','Product / Model')}{person('owner_id','Business Owner')}{person('technical_owner_id','Technical Owner')}{input('provider','Provider')}<Field label="Related Vendor"><select className={SELECT} value={form.vendor_id||''} onChange={e=>put('vendor_id',e.target.value||null)}><option value="">No vendor linked</option>{(context?.options.vendors||[]).map(v=><option key={v.vendor_id} value={v.vendor_id}>{v.name}</option>)}</select></Field><Field label="Status"><select className={SELECT} value={form.status} onChange={e=>put('status',e.target.value)}>{catalog.statuses.filter(v=>admin||!['active','suspended','retired'].includes(v)||v===form.status).map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></Field></div>{input('description','Description',true)}<Choices label="Purpose / Use" values={catalog.purposes} selected={form.purposes} onChange={v=>put('purposes',v)}/><Choices label="Data categories" values={catalog.data_types} selected={form.data_types} onChange={v=>put('data_types',v)}/><Choices label="System access" values={catalog.access} selected={form.access} onChange={v=>put('access',v)}/></>:<><p className="text-sm">Governance Risk Tier: <strong className="capitalize">{screen.risk_tier||'Not screened'}</strong> · {screen.screening_complete?'Screening complete':'Screening incomplete'}</p><p className="text-xs text-ink-muted">Omnisciente screening: consequential/HR decisions, autonomous action or material harm indicate High. Other exposure indicates Moderate; Low requires complete answers. Not an EU AI Act classification or a Risk Register score.</p><div className="grid sm:grid-cols-2 gap-4">{catalog.questions.map(q=><div key={q.key}>{boolean(q.label,form.screening[q.key],v=>put('screening',{...form.screening,[q.key]:v}))}</div>)}{boolean('Human review required?',form.human_review_required,v=>put('human_review_required',v))}{boolean('Human approval before action required?',form.human_approval_required,v=>put('human_approval_required',v))}{person('oversight_owner_id','Oversight Owner')}</div>{input('oversight_notes','Human oversight approach / notes',true)}<Choices label="Organizational role (not legal applicability)" values={catalog.roles} selected={form.roles} onChange={v=>put('roles',v)}/><details><summary className="text-sm cursor-pointer">Optional AI risk topics</summary><Choices label="Screening topics — link material exposures to Risks" values={catalog.risk_topics} selected={form.risk_topics} onChange={v=>put('risk_topics',v)}/></details>{input('governance_notes','Governance notes',true)}</>}
    </fieldset>{id&&tab==='Overview'&&<div className="text-sm text-ink-muted border-t border-line pt-3">Created: {record.created_at?.slice(0,10)} · Last Review: {current?.last_review?.slice(0,10)||'Never reviewed'} · Next Review: {current?.next_review?.slice(0,10)||'Not scheduled'} · Cadence: {current?.review_cadence||'Not configured'}</div>}{editable&&<Button disabled={busy} type="submit">{busy?'Saving…':id?'Save AI System':'Create AI System'}</Button>}</form>}
    {id&&tab==='Risk & Governance'&&<section className="mt-6 space-y-3"><h3 className="text-sm font-semibold">Program Health</h3><p className="text-xs text-ink-muted">Deterministic governance attention signals—not Findings or compliance failures. These clear when the underlying conditions are corrected.</p>{current?.alerts?.length?<ul className="space-y-2 text-sm">{current.alerts.map(a=><li key={a.key} className="border-l-2 border-semantic-duesoon pl-3">{a.label}</li>)}</ul>:<p className="text-sm text-ink-muted">{context?'No current AI governance alerts.':'Loading governance context…'}</p>}</section>}
    {tab==='Reviews'&&<div className="space-y-4"><p className="text-sm text-ink-muted">These are central Reviews. Open one to start/complete it, inspect occurrence history, attach Evidence, or raise a Finding and remediation Action Item.</p>{recordList('reviews',related.reviews||[])}{!related.reviews?.length&&<p className="text-sm">No linked Reviews yet.</p>}{admin&&editable&&form.status!=='suspended'&&!related.reviews?.some(r=>r.ai_review_purpose==='periodic'&&!['completed','cancelled'].includes(r.status))&&<fieldset disabled={busy} className="border border-line rounded p-4 space-y-3"><h3 className="text-sm font-semibold">Schedule governance review</h3><p className="text-xs text-ink-muted">Cadence is an internal choice, not a claimed external requirement.</p><Field label="Review due date"><Input type="date" value={schedule.due_date} onChange={e=>setSchedule({...schedule,due_date:e.target.value})}/></Field><Field label="Review cadence"><select className={SELECT} value={schedule.recurrence} onChange={e=>setSchedule({...schedule,recurrence:e.target.value})}>{['quarterly','semiannual','annual','custom'].map(v=><option key={v}>{v}</option>)}</select></Field>{schedule.recurrence==='custom'&&<Field label="Custom recurrence days"><Input type="number" min="1" max="3650" value={schedule.custom_recurrence_days} onChange={e=>setSchedule({...schedule,custom_recurrence_days:Number(e.target.value)})}/></Field>}<Button onClick={()=>run(()=>api.post(`/ai_systems/${id}/reviews`,schedule))}>Schedule Review</Button></fieldset>}{admin&&editable&&<fieldset disabled={busy} className="space-y-3 border border-line p-4 rounded"><h3 className="text-sm font-semibold">Material change requires reassessment</h3><p className="text-xs text-ink-muted">Record a significant change, then open the linked Review to reassess or adjust its date. Recording a change does not duplicate a Review.</p><Field label="Material change description"><Textarea value={change} onChange={e=>setChange(e.target.value)}/></Field><Button variant="outline" onClick={()=>run(async()=>{await api.post(`/ai_systems/${id}/material-change`,{note:change});setChange('');})}>Record Material Change</Button>{current?.material_change_note&&<p className="text-sm">Latest: {current.material_change_note}</p>}</fieldset>}</div>}
    {tab==='Related'&&<div className="space-y-4">{Object.entries(related).filter(([k,v])=>IDS[k]&&k!=='reviews'&&v.length).map(([k,v])=><section key={k}><h3 className="text-sm font-semibold capitalize mb-2">{k==='tasks'?'Action Items':k}</h3>{recordList(k,v)}</section>)}{editable&&<fieldset disabled={busy} className="border border-line rounded p-4 space-y-3"><h3 className="text-sm font-semibold">Link an existing authoritative record</h3><Field label="Record type"><select className={SELECT} value={link.kind} onChange={e=>setLink({kind:e.target.value,id:'',classification:'Context',source:'',rationale:''})}>{['risks','findings','tasks','policies','requirements','vendors'].map(k=><option key={k} value={k}>{k==='tasks'?'Action Items':k}</option>)}</select></Field><Field label="Record"><select className={SELECT} value={link.id} onChange={e=>setLink({...link,id:e.target.value})}><option value="">Select record</option>{(context?.options[link.kind]||[]).map(r=><option key={r[IDS[link.kind]]} value={r[IDS[link.kind]]}>{r.display_id?`${r.display_id} · `:''}{r.title||r.name}</option>)}</select></Field>{link.kind==='requirements'&&<><Field label="Mapping classification"><select className={SELECT} value={link.classification} onChange={e=>setLink({...link,classification:e.target.value})}>{catalog.relationship_classes.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Authoritative source / citation"><Input value={link.source} onChange={e=>setLink({...link,source:e.target.value})}/></Field><Field label="Applicability rationale"><Textarea value={link.rationale} onChange={e=>setLink({...link,rationale:e.target.value})}/></Field></>}<Button variant="outline" onClick={()=>run(()=>api.post(`/ai_systems/${id}/links`,link))}>Link Record</Button><div className="flex flex-wrap gap-2 pt-3 border-t border-line">{[['risks','Create Risk'],['tasks','Create Action Item'],['policies','Create recommended AI Policy']].map(([kind,label])=><Button key={kind} variant="outline" onClick={()=>setNested({kind,create:true,initialValues:{title:kind==='policies'?'AI Governance and Acceptable Use Policy':`Governance follow-up — ${record.name}`,client_id:clientId,...(kind==='risks'?{category:'ai_governance'}:{}),...(kind==='policies'?{summary:'Recommended internal governance practice. Determine applicable requirements separately.'}:{})}})}>{label}</Button>)}</div></fieldset>}{current?.related_links?.filter(l=>l.kind==='requirements').map((l,i)=><p className="text-xs text-ink-muted" key={i}>{l.classification} · {l.rationale||'No applicability claim'} · {l.source||'No external source recorded'}</p>)}</div>}
    {tab==='Evidence'&&<div className="space-y-4"><p className="text-sm text-ink-muted">Existing Evidence Library records, including evidence on linked Review occurrences. No second file repository.</p>{editable&&<Field label="Attach evidence"><input type="file" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></Field>}<ul className="space-y-2">{(related.evidence||[]).map(e=><li key={e.evidence_id} className="border border-line rounded p-3 text-sm"><button className="text-link" onClick={()=>download(e)}>{e.filename}</button><span className="text-xs text-ink-muted ml-2">{e.created_at?.slice(0,10)} · {e.linked_type}</span></li>)}</ul>{!related.evidence?.length&&<p className="text-sm">No linked evidence.</p>}</div>}
    {tab==='Activity'&&<ul className="space-y-3">{(context?.activity||[]).map((a,i)=><li key={a.audit_id||a.log_id||i} className="text-sm border-b border-line pb-3"><p>{a.action}</p><p className="text-xs text-ink-muted">{a.at} · {a.user_name||a.user_email}</p></li>)}</ul>}
  </SheetContent></Sheet>{nested&&<RecordDrawer {...nested} open clientId={clientId} users={users} schema={SCHEMAS[nested.kind]?.fields} onOpenChange={v=>{if(!v){setNested(null);setRevision(n=>n+1);}}} onSaved={async saved=>{if(nested.create&&saved?.[IDS[nested.kind]]){try{await api.post(`/ai_systems/${id}/links`,{kind:nested.kind,id:saved[IDS[nested.kind]],classification:nested.kind==='policies'?'Recommended governance practice':'Context'});}catch(e){setError('Record saved, but linking failed: '+formatError(e));}}setRevision(n=>n+1);}}/>}</>;
}
