import {riskCategories,riskTreatments,pilotRiskStatus} from '@/lib/brawndoRisks';
import {assessedRisk} from '@/lib/grcWork';
import {displayDay} from '@/lib/managementDates';
import {personLabel} from '@/lib/people';
import {Input} from './ui/input';
import {Label} from './ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from './ui/select';

export function RiskCategoryField({form,setForm,disabled=false}){return <div className="space-y-2"><Label>Category</Label><Select disabled={disabled} value={form.category||''} onValueChange={category=>setForm({...form,category})}><SelectTrigger aria-label="Risk category"><SelectValue placeholder="Select category"/></SelectTrigger><SelectContent>{form.category&&!riskCategories[form.category]&&<SelectItem value={form.category}>{form.category} (recorded)</SelectItem>}{Object.entries(riskCategories).map(([v,label])=><SelectItem key={v} value={v}>{label}</SelectItem>)}</SelectContent></Select>{form.category==='other'&&<><Label htmlFor="risk-category-other">Other category description</Label><Input id="risk-category-other" maxLength={200} disabled={disabled} value={form.category_other||''} onChange={e=>setForm({...form,category_other:e.target.value})}/></>}</div>;}
export function RiskTreatmentField({form,setForm,disabled=false}){return <div className="space-y-2"><Label>Treatment decision</Label><Select disabled={disabled} value={form.treatment||'undecided'} onValueChange={v=>setForm({...form,treatment:v==='undecided'?'':v})}><SelectTrigger aria-label="Treatment decision"><SelectValue/></SelectTrigger><SelectContent>{form.treatment&&!riskTreatments[form.treatment]&&<SelectItem value={form.treatment}>{form.treatment} (legacy; retained)</SelectItem>}{Object.entries(riskTreatments).map(([v,label])=><SelectItem key={v} value={v||'undecided'}>{label}</SelectItem>)}</SelectContent></Select>{form.treatment==='accept'&&form.status!=='accepted'&&<p className="text-sm text-ink-secondary">Proposed acceptance only. An authorized approver must use Accept Risk to record the decision.</p>}{form.treatment==='monitor'&&<p className="text-sm text-ink-secondary">Legacy monitoring treatment retained. Monitoring is now a lifecycle status; choose a treatment only when a decision is made.</p>}</div>;}
export function RiskSummary({risk,users,statusLabel=pilotRiskStatus(risk.status)}){const rated=assessedRisk(risk);return <dl className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-5 pb-4 border-b border-line text-sm">{[['Level',rated.risk_level||'Needs assessment'],['Current assessed score',rated.risk_score??'—'],['Status',statusLabel],['Assigned Owner',personLabel(users,risk.owner_id,'Unassigned')],['Treatment',riskTreatments[risk.treatment||'']||`${risk.treatment} (legacy)`],['Next Review',displayDay(risk.next_review)||'Not scheduled']].map(([label,value])=><div key={label}><dt className="text-ink-secondary text-xs">{label}</dt><dd className="font-medium capitalize mt-1">{value}</dd></div>)}</dl>;}
