import {useState} from 'react';
import api,{formatError} from '@/lib/api';
import {useAuth} from '@/context/AuthContext';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Button} from './ui/button';
import {EvidenceSource,downloadEvidence,uploaderLabel} from '@/lib/evidenceContext';
import {MetadataFields,SourcePicker,useLibraryRequest,selectClass} from './EvidenceLibraryControls';
import {evidenceSources} from '@/lib/evidenceReferences';
import {toast} from 'sonner';

export default function EvidenceItemDrawer({id,onClose,onOpen,onChanged}){
  const {user}=useAuth(),[refresh,setRefresh]=useState(0),[tab,setTab]=useState('Overview'),[draft,setDraft]=useState(null),[draftVersion,setDraftVersion]=useState(null),[kind,setKind]=useState('findings'),[busy,setBusy]=useState(false),[activityPage,setActivityPage]=useState(1);
  const {data:item,error,loading}=useLibraryRequest(`/evidence-library/items/${encodeURIComponent(id)}`,{},refresh);
  const activity=useLibraryRequest(tab==='Activity'?`/evidence-library/items/${encodeURIComponent(id)}/activity`:null,{page:activityPage},refresh);
  const canWrite=!item?.archived_at&&['super_admin','platform_admin','client_contributor'].includes(user?.role),canDelete=!item?.archived_at&&['super_admin','platform_admin'].includes(user?.role);
  const changed=()=>{setRefresh(v=>v+1);onChanged();};
  async function mutate(fn){setBusy(true);try{await fn();changed();return true;}catch(e){toast.error(formatError(e));return false;}finally{setBusy(false);}}
  async function link(ref,remove=false){await mutate(()=>ref.kind==='framework_assessments'?api.post(`/framework_assessments/${ref.id}/links`,{kind:'evidence',id}):api.post(`/evidence-library/items/${id}/relationships`,{linked_type:ref.kind,linked_id:ref.id,occurrence_id:ref.occurrence_id||null,remove,expected_updated_at:item.updated_at||null}));}
  async function remove(){if(!window.confirm(`Delete "${item.filename}" from the library? It has ${item.references.length} source/supporting references. Retained history and bytes are not erased; retention rules may prevent deletion.`))return;if(await mutate(()=>api.delete(`/evidence/${id}`)))onClose();}
  return <Sheet open onOpenChange={v=>{if(!v)onClose();}}><SheetContent className="w-full sm:max-w-xl overflow-y-auto"><SheetHeader><SheetTitle>{item?.display_name||item?.filename||'Evidence Item'}</SheetTitle><SheetDescription>One authoritative file · source and supporting relationships</SheetDescription></SheetHeader>
    {loading&&<p role="status">Loading Evidence…</p>}{error&&<p role="alert">{error}</p>}
    {item&&!loading&&<div className="space-y-4 pt-4"><div role="group" aria-label="Evidence detail" className="flex border-b border-line">{['Overview','Related','Activity'].map(t=><button key={t} aria-pressed={tab===t} className={`px-3 py-2 text-sm ${tab===t?'font-semibold border-b-2 border-brand-charcoal':'text-ink-secondary hover:bg-surface-subtle'}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
      {tab==='Overview'&&<section aria-label="Evidence overview" className="space-y-4"><dl className="grid grid-cols-2 gap-3 text-sm">{[['Filename',item.filename],['Program Area',item.program_areas?.join(', ')],['Evidence Type',item.evidence_type||'Other'],['Uploaded by',uploaderLabel(item)],['Uploaded',item.created_at?new Date(item.created_at).toLocaleString():'Not recorded'],['File type',item.mime_type],['Size',item.size!=null?`${item.size.toLocaleString()} bytes`:'Not recorded'],['Artifact version',item.version],['Evidence date',item.evidence_date],['Effective date',item.effective_date],['Expiration date',item.expiration_date],['Refresh date',item.refresh_date]].filter(([,v])=>v!=null).map(([k,v])=><div key={k}><dt className="text-xs text-ink-secondary">{k}</dt><dd className="break-words">{v}</dd></div>)}</dl><p className="text-xs break-all text-ink-secondary">SHA-256: {item.sha256||'Not recorded'}</p>{item.notes&&<p className="text-sm whitespace-pre-wrap">{item.notes}</p>}
        <Button variant="outline" onClick={()=>downloadEvidence(item).catch(e=>toast.error(formatError(e)))}>Download file</Button>
        <p className="text-xs text-ink-secondary">File bytes are immutable. Upload replacements from the source module; Policy approval/version history stays in Policies.</p>
        {canWrite&&!draft&&<Button variant="outline" onClick={()=>{setDraftVersion(item.updated_at||null);setDraft(Object.fromEntries(['display_name','evidence_type','evidence_date','effective_date','expiration_date','refresh_date','notes'].map(k=>[k,item[k]||null])));}}>Edit classification</Button>}
        {draft&&<form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(await mutate(()=>api.patch(`/evidence-library/items/${id}`,{...draft,evidence_type:draft.evidence_type||'Other',expected_updated_at:draftVersion})))setDraft(null);}}><MetadataFields value={draft} onChange={setDraft}/><div className="flex gap-2"><Button disabled={busy}>Save classification</Button><Button type="button" variant="outline" onClick={()=>setDraft(null)}>Cancel</Button></div></form>}
        {canDelete&&<div><button className="text-sm text-semantic-critical underline" disabled={busy} onClick={remove}>Delete Evidence Item</button></div>}
      </section>}
      {tab==='Related'&&<section aria-label="Evidence relationships" className="space-y-4"><p className="text-xs text-ink-secondary">Unlink removes only a supporting relationship. Original upload provenance and module-owned history remain intact.</p>{!item.references.length&&<p>No relationships. This Evidence needs classification.</p>}{item.references.map((ref,i)=><div key={`${ref.kind}:${ref.id}:${ref.occurrence_id}:${i}`} className="border border-line rounded-md p-3 space-y-2"><EvidenceSource source={ref} onOpen={onOpen}/>{ref.document_context&&<p className="text-xs text-ink-secondary">{ref.document_context}</p>}<div className="flex justify-between gap-2 text-xs text-ink-secondary"><span>{ref.origin==='upload'?'Original upload source':ref.origin==='supporting'?'Supporting relationship':'Managed in the source module'}</span>{canWrite&&ref.origin==='supporting'&&ref.available&&<button className="underline" disabled={busy} onClick={()=>{if(window.confirm(`Unlink from ${ref.title}? The file and other relationships remain.`))link(ref,true);}}>Unlink</button>}</div></div>)}
        {canWrite&&<details><summary className="cursor-pointer text-sm font-medium">Link another record</summary><div className="space-y-3 pt-3"><label className="block text-sm">Record type<select aria-label="Record type" className={selectClass} value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(evidenceSources).map(([k,s])=><option key={k} value={k}>{s.label}</option>)}</select></label><fieldset disabled={busy}><SourcePicker key={kind} clientId={item.client_id} kind={kind} onSelect={ref=>link(ref)}/></fieldset></div></details>}
      </section>}
      {tab==='Activity'&&<section aria-label="Evidence activity" className="space-y-3">{activity.loading&&<p>Loading activity…</p>}{activity.error&&<p role="alert">{activity.error}</p>}{activity.data?.items.map((event,i)=><div key={event.log_id||event.audit_id||i} className="border-b border-line py-2 text-sm"><p>{event.action}</p><p className="text-xs text-ink-secondary">{event.user_name||event.user_email||'Recorded actor'} · {event.at?new Date(event.at).toLocaleString():'Not recorded'}</p></div>)}{activity.data?.total===0&&<p>No recorded activity available.</p>}<div className="flex gap-2"><Button variant="outline" disabled={activityPage===1} onClick={()=>setActivityPage(activityPage-1)}>Previous events</Button><Button variant="outline" disabled={!activity.data||activityPage*25>=activity.data.total} onClick={()=>setActivityPage(activityPage+1)}>Next events</Button></div></section>}
    </div>}
  </SheetContent></Sheet>;
}
