import {useEffect,useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from './ui/sheet';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import api,{formatError} from '@/lib/api';
import {useAuth} from '@/context/AuthContext';
import {frameworkCatalog,frameworkDefinition,ASSESSMENT_STATUSES,REQUIREMENT_TYPES,SPECIFICATION_LABELS} from '@/lib/frameworks';
import {recordUuid} from '@/lib/recordUuid';
import policyCatalog from '@/lib/onboardingCatalog.json';
import {actionStatus} from '@/lib/actionItems';
import {SCHEMAS} from '@/lib/schemas';
import RecordDrawer from './RecordDrawer';
import AssigneeSelect from './AssigneeSelect';

const IDS={reviews:'review_id',findings:'finding_id',tasks:'task_id',risks:'risk_id',policies:'policy_id',requirements:'requirement_id',evidence:'evidence_id',vendors:'vendor_id'};
const SELECT='w-full border border-line bg-surface-card rounded p-2 text-sm';
const readFile=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
export default function FrameworkDrawer({open,onOpenChange,record,clientId,onSaved}){
  const {user}=useAuth(),aid=record.framework_assessment_id,definition=frameworkDefinition(record.framework_key,record.definition_id);
  const catalog=frameworkCatalog(record.framework_key),isCis=record.framework_key==='cis-ig1',item=isCis?'Safeguard':'Requirement',program=isCis?'CIS':'HIPAA';
  const writable=['super_admin','platform_admin','client_contributor'].includes(user?.role);
  const [tab,setTab]=useState('Overview'),[form,setForm]=useState(record),[ctx,setCtx]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[nested,setNested]=useState(null),[comment,setComment]=useState(''),[finding,setFinding]=useState(null),[link,setLink]=useState({kind:'risks',id:''});
  useEffect(()=>{
    const c=new AbortController();setCtx(null);setError('');const opts={params:{client_id:clientId},signal:c.signal};
    Promise.all([api.get(`/framework_assessments/${aid}/related`,{signal:c.signal}),api.get('/clients/'+clientId+'/members',{signal:c.signal}),api.get('/contacts',opts),api.get('/comments',{params:{entity_type:'framework_assessments',entity_id:aid},signal:c.signal}),api.get(`/framework_assessments/${aid}/activity`,{signal:c.signal}),api.get('/frameworks/'+record.framework_key,opts),Promise.all(Object.keys(IDS).map(async k=>[k,(await api.get('/'+k,opts)).data]))]).then(([related,users,contacts,comments,activity,workspace,options])=>{
      if(!c.signal.aborted)setCtx({related:related.data,users:users.data,contacts:contacts.data,comments:comments.data,activity:activity.data,current:workspace.data.assessments.find(a=>a.framework_assessment_id===aid),options:Object.fromEntries(options)});
    }).catch(e=>{if(!c.signal.aborted)setError(formatError(e));});return()=>c.abort();
  },[aid,clientId,record.framework_key,revision]);
  async function run(fn){setBusy(true);setError('');try{await fn();setRevision(n=>n+1);onSaved?.();}catch(e){setError(formatError(e));}finally{setBusy(false);}}
  const put=(key,value)=>setForm(p=>({...p,[key]:value}));
  const who=id=>ctx?.users.find(u=>u.user_id===id)?.name||'Unassigned';
  async function save(){await run(async()=>{const body=Object.fromEntries(['status','implementation','technology','notes','na_rationale','owner_id','process_owner_id','addressable_decision','addressable_rationale'].map(k=>[k,form[k]??(k.endsWith('_id')?null:'')]));const {data}=await api.patch(`/framework_assessments/${aid}`,body);setForm(data);});}
  async function download(e){await run(async()=>{const {data}=await api.get(`/evidence/${e.evidence_id}/download`);const a=document.createElement('a');a.href=data.content_base64.startsWith('data:')?data.content_base64:`data:${data.mime_type};base64,${data.content_base64}`;a.download=data.filename;a.click();});}
  const current=ctx?.current||record,related=ctx?.related||{};
  return <><Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="w-full sm:max-w-3xl overflow-y-auto bg-surface-card" data-testid="framework-drawer"><SheetHeader><SheetTitle>{program} {definition.id} · {definition.title}</SheetTitle><SheetDescription>Document implementation and link proof. Addressed is not an audit opinion.</SheetDescription></SheetHeader>
    <div className="flex gap-2 overflow-x-auto border-b border-line my-4" role="tablist" aria-label={`${item} sections`}>{['Overview','Implementation','Related','Evidence','Comments','Activity'].map(t=><button key={t} role="tab" aria-selected={t===tab} className={`drawer-tab whitespace-nowrap ${tab===t?'active':''}`} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {error&&<p role="alert" className="text-sm text-semantic-critical mb-3">{error}</p>}
    {tab==='Overview'&&<div className="space-y-4 text-sm"><dl className="grid grid-cols-2 gap-3">{[['Framework version',catalog.version],...(isCis?[['Implementation Group','IG1']]:[['Classification',definition.classification],['Specification',SPECIFICATION_LABELS[definition.specification]]]),[isCis?'Control':'Section',`${definition.control} · ${definition.control_name}`],[item,definition.id],['Requirement type',REQUIREMENT_TYPES[definition.type]],['Source cadence',definition.source_cadence],['Status',ASSESSMENT_STATUSES[current.status]],['Owner',who(current.owner_id)],['Last assessed',current.last_assessed?.slice(0,10)||'Not assessed'],['Assessed by',current.assessed_by?who(current.assessed_by):'—']].map(([k,v])=><div key={k}><dt className="text-xs text-ink-muted">{k}</dt><dd>{v}</dd></div>)}</dl><p className="border-t border-line pt-4 whitespace-pre-wrap">{definition.guidance}</p>{definition.evidence_guidance&&<p>{definition.evidence_guidance}</p>}<a className="text-link underline" href={definition.source} target="_blank" rel="noreferrer">Official {program} source · {item.toLowerCase()} {definition.id}</a><p className="text-xs text-ink-muted">Concise implementation prompt. Consult the official source for full scope and qualifications.</p></div>}
    {tab==='Implementation'&&<fieldset disabled={!writable||busy} className="space-y-4"><label className="block text-sm">How We Address This {item}<Textarea aria-label={`How We Address This ${item}`} value={form.implementation||''} onChange={e=>put('implementation',e.target.value)}/></label>{definition.specification==='addressable'&&<div className="space-y-3"><p className="text-sm">{definition.decision_guidance}</p><label className="block text-sm">Addressability decision<select aria-label="Addressability decision" className={SELECT} value={form.addressable_decision||''} onChange={e=>put('addressable_decision',e.target.value)}><option value="">Not yet determined</option><option value="as_written">Implement as written</option><option value="equivalent_alternative">Equivalent alternative</option><option value="not_reasonable_appropriate">Neither is reasonable and appropriate</option></select></label><label className="block text-sm">Decision rationale<Textarea aria-label="Decision rationale" maxLength={4000} value={form.addressable_rationale||''} onChange={e=>put('addressable_rationale',e.target.value)}/></label></div>}<label className="block text-sm">Technology / Products<Input aria-label="Technology / Products" value={form.technology||''} onChange={e=>put('technology',e.target.value)}/></label><div className="grid sm:grid-cols-2 gap-3"><div className="text-sm">Assessment Owner<AssigneeSelect clientId={clientId} label="Assessment Owner" value={form.owner_id} onChange={v=>put('owner_id',v)} users={ctx?.users||[]} disabled={!writable||busy}/></div><label className="block text-sm">Process Owner (Contact)<select aria-label="Process Owner (Contact)" className={SELECT} value={form.process_owner_id||''} onChange={e=>put('process_owner_id',e.target.value||null)}><option value="">Unassigned</option>{ctx?.contacts.map(c=><option key={c.contact_id} value={c.contact_id}>{c.name}</option>)}</select><span className="block mt-1.5 text-xs text-ink-secondary">Business responsibility only; does not grant platform access.</span></label></div><label className="block text-sm">Implementation Notes<Textarea aria-label="Implementation Notes" value={form.notes||''} onChange={e=>put('notes',e.target.value)}/></label><label className="block text-sm">Status<select aria-label="Assessment Status" className={SELECT} value={form.status} onChange={e=>put('status',e.target.value)}>{Object.entries(ASSESSMENT_STATUSES).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>{form.status==='not_applicable'&&<label className="block text-sm">N/A Rationale (required)<Textarea aria-label="N/A Rationale" value={form.na_rationale||''} onChange={e=>put('na_rationale',e.target.value)}/></label>}<p className="text-xs text-ink-muted">Evidence, completed Actions and closed Findings do not automatically mark this {item.toLowerCase()} Addressed.</p>{writable&&<Button onClick={save}>{busy?'Saving…':'Save assessment'}</Button>}</fieldset>}
    {tab==='Related'&&<div className="space-y-5">{!!catalog.policy_mappings.filter(m=>m.safeguards.includes(definition.id)).length&&<section className="space-y-2"><h3 className="text-sm font-semibold">Supporting policy areas</h3><p className="text-xs text-ink-secondary">These are support mappings, not prescribed document titles or automatic proof of effectiveness.</p>{catalog.policy_mappings.filter(m=>m.safeguards.includes(definition.id)).map((m,i)=>{const policies=(related.policies||[]).filter(p=>p.baseline_key===m.policy_key);return <div className="border border-line rounded p-3 text-sm" key={m.policy_key+i}><p className="font-medium">{policyCatalog.policies.find(p=>p.key===m.policy_key)?.name||m.policy_key}</p><p className="text-xs text-ink-secondary">{m.basis||m.classification} · {m.rationale||m.reason}</p>{ctx&&(policies.length?policies.map(p=><button key={p.policy_id} className="block text-link text-left mt-1" onClick={()=>setNested({kind:'policies',record:p})}>{p.title} · {p.presence?.replaceAll('_',' ')||'Presence not verified'} · {p.status?.replaceAll('_',' ')}</button>):<p className="mt-1 text-ink-secondary">No policy mapped to this area. Link an existing Policy below or manage the gap in Policies.</p>)}</div>;})}</section>}{Object.entries(related).filter(([k,v])=>k!=='evidence'&&v.length).map(([kind,rows])=><section key={kind}><h3 className="text-sm font-semibold capitalize mb-2">{kind==='tasks'?'Action Items':kind}</h3><ul className="space-y-2">{rows.map(r=><li key={r[IDS[kind]]} className="border border-line rounded p-3 text-sm"><button className="text-link text-left" onClick={()=>setNested({kind,record:r})}>{r.title||r.name}</button><p className="text-xs text-ink-muted">{kind==='tasks'?actionStatus(r.status):r.status==='remediated'?'Pending Validation':r.status?.replaceAll('_',' ')}{kind==='reviews'&&` · Next: ${r.due_date?.slice(0,10)||'Needs scheduling'} · Last: ${r.occurrences?.at(-1)?.completed_at?.slice(0,10)||'No completed occurrence'} · Outcome: ${r.occurrences?.at(-1)?.outcome||'—'}`}</p></li>)}</ul></section>)}{ctx&&!Object.values(related).some(v=>v.length)&&<p className="text-sm text-ink-muted">No related records yet.</p>}
      {writable&&<fieldset disabled={busy} className="space-y-3 border-t border-line pt-4"><Button variant="outline" onClick={()=>setFinding({title:'',description:'',remediation_title:'',severity:'medium',request_id:recordUuid()})}>Raise Finding</Button>{finding&&<div className="space-y-3 border border-line rounded p-4"><p className="text-xs text-ink-muted">Source: {program} · {definition.id}. Creates one normal Finding and one remediation Action Item.</p>{[['title','Finding title'],['remediation_title','Remediation Action title'],['description','Finding description']].map(([k,label])=><label className="block text-sm" key={k}>{label}<Input aria-label={label} value={finding[k]} onChange={e=>setFinding({...finding,[k]:e.target.value})}/></label>)}<label className="block text-sm">Severity<select aria-label="Finding severity" className={SELECT} value={finding.severity} onChange={e=>setFinding({...finding,severity:e.target.value})}>{['low','medium','high','critical'].map(s=><option key={s}>{s}</option>)}</select></label><Button onClick={()=>run(async()=>{await api.post(`/framework_assessments/${aid}/findings`,finding);setFinding(null);})}>Create Finding & Action</Button></div>}
        <h3 className="text-sm font-semibold">Link an existing record</h3><label className="block text-sm">Record type<select aria-label="Related record type" className={SELECT} value={link.kind} onChange={e=>setLink({kind:e.target.value,id:''})}>{Object.keys(IDS).filter(k=>k!=='evidence').map(k=><option key={k} value={k}>{k==='tasks'?'Action Items':k}</option>)}</select></label><label className="block text-sm">Record<select aria-label="Related record" className={SELECT} value={link.id} onChange={e=>setLink({...link,id:e.target.value})}><option value="">Select record</option>{ctx?.options[link.kind].map(r=><option key={r[IDS[link.kind]]} value={r[IDS[link.kind]]}>{r.title||r.name}</option>)}</select></label><Button variant="outline" onClick={()=>run(()=>api.post(`/framework_assessments/${aid}/links`,link))}>Link record</Button></fieldset>}
    </div>}
    {tab==='Evidence'&&<div className="space-y-4"><p className="text-sm text-ink-muted">One Evidence Library item, linked to this {item.toLowerCase()}. Evidence from mapped Review occurrences is also shown. Unlink removes this assessment’s current relationship only; the Library artifact and original provenance are retained.</p>{writable&&<fieldset disabled={busy} className="space-y-3"><label className="block text-sm">Upload Evidence<input type="file" aria-label="Upload Evidence" onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>api.post('/evidence',{client_id:clientId,linked_type:'framework_assessment',linked_id:aid,filename:f.name,mime_type:f.type||'application/octet-stream',content_base64:await readFile(f)}));}}/></label><label className="block text-sm">Link existing Evidence<select aria-label="Link existing Evidence" className={SELECT} defaultValue="" onChange={e=>{const id=e.target.value;if(id)run(()=>api.post(`/framework_assessments/${aid}/links`,{kind:'evidence',id}));}}><option value="">Select Evidence Library item</option>{ctx?.options.evidence.map(e=><option key={e.evidence_id} value={e.evidence_id}>{e.filename}</option>)}</select></label></fieldset>}<ul className="space-y-2">{related.evidence?.map(e=><li className="text-sm border border-line rounded p-3" key={e.evidence_id}><button className="text-link" onClick={()=>download(e)}>{e.filename}</button><p className="text-xs text-ink-muted">{e.created_at?.slice(0,10)} · {e.linked_type}</p>{writable&&<Button variant="ghost" disabled={busy} aria-label={`Unlink ${e.filename} from this assessment`} onClick={()=>run(()=>api.delete(`/framework_assessments/${aid}/links`,{data:{kind:'evidence',id:e.evidence_id}}))}>Unlink from assessment</Button>}</li>)}</ul>{ctx&&!related.evidence?.length&&<p className="text-sm">No linked Evidence.</p>}</div>}
    {tab==='Comments'&&<div className="space-y-4"><ul className="space-y-3">{ctx?.comments.map(c=><li key={c.comment_id} className="border-b border-line pb-3 text-sm"><p>{c.body}</p><p className="text-xs text-ink-muted">{c.author_name||c.user_name} · {c.created_at}</p></li>)}</ul>{writable&&<><Textarea aria-label={`${item} comment`} value={comment} onChange={e=>setComment(e.target.value)}/><Button disabled={busy||!comment.trim()} onClick={()=>run(async()=>{await api.post('/comments',{client_id:clientId,entity_type:'framework_assessments',entity_id:aid,body:comment});setComment('');})}>Add comment</Button></>}</div>}
    {tab==='Activity'&&<div className="space-y-5"><h3 className="text-sm font-semibold">Assessment history · {current.assessment_history?.length||0}</h3><ul className="space-y-3">{current.assessment_history?.slice().reverse().map((h,i)=><li className="text-sm border-b border-line pb-3" key={i}><p>{ASSESSMENT_STATUSES[h.status]} · {h.at} · {who(h.by)}</p><p className="text-xs text-ink-muted whitespace-pre-wrap">{h.implementation}{h.addressable_decision&&` · ${h.addressable_decision}: ${h.addressable_rationale}`}{h.na_rationale&&` · N/A: ${h.na_rationale}`}</p></li>)}</ul><h3 className="text-sm font-semibold">Activity</h3><ul className="space-y-2">{ctx?.activity.map((a,i)=><li key={a.audit_id||i} className="text-sm">{a.action}<p className="text-xs text-ink-muted">{a.at} · {a.user_name||a.user_email}</p></li>)}</ul></div>}
  </SheetContent></Sheet>{nested&&<RecordDrawer {...nested} open clientId={clientId} users={ctx?.users||[]} schema={SCHEMAS[nested.kind]?.fields} onOpenChange={v=>{if(!v){setNested(null);setRevision(n=>n+1);}}} onSaved={()=>setRevision(n=>n+1)}/>}</>;
}
