import {operatorGuidance,operatorProgram} from '@/lib/frameworkOperator';
import {REQUIREMENT_TYPES,SPECIFICATION_LABELS} from '@/lib/frameworks';
import {sourcePresentation,recurrencePresentation} from '@/lib/frameworkWorkspace';

export default function FrameworkContext({framework,definition,catalog,related,loading}){
  const guide=operatorGuidance(framework,definition),source=sourcePresentation(definition),official=source.mode!=='REFERENCE_ONLY',cadence=recurrencePresentation(definition,catalog);
  const plans=catalog.review_plans.filter(p=>p.safeguards.includes(definition.id));
  return <section className="space-y-3 text-sm" aria-label="Requirement context">
    <div className="border-l-2 border-line-strong pl-3 text-sm text-ink-secondary"><h3 className="font-semibold mb-1">Framework Reference</h3><p>{operatorProgram(framework)} · Version {catalog.version} · {source.citation}</p><p>{definition.control_name}</p>{source.url&&<a className="text-link underline inline-block mt-2" href={source.url} target="_blank" rel="noopener noreferrer">Open official reference ↗</a>}</div>
    {definition.specification&&<p className="text-xs font-medium text-ink-secondary">{SPECIFICATION_LABELS[definition.specification]}{definition.specification==='addressable'?' · Addressable does not mean optional. Record the decision and rationale below.':''}</p>}
    <div><h3 className="font-semibold">{official?'Official Requirement':'Authoritative Source'}</h3><p className="mt-2 whitespace-pre-wrap">{official?source.text:'Reference-only presentation. Consult the official source for complete authoritative wording; the guidance below is not official framework text.'}</p>{source.mode==='LICENSED_TEXT'&&<p className="text-xs">Licensed text</p>}</div>
    <div><h3 className="font-semibold">Implementation Guidance</h3><p className="mt-1 whitespace-pre-wrap">{guide.meaning}</p><p className="mt-2">{guide.implementation}</p><p className="mt-1 text-xs text-ink-secondary">Omnisciente guidance · {official?'Explanation, separate from the regulatory text.':'Summary, not verbatim framework text. Consult the reference for full wording and scope.'}</p></div>
    {framework==='iso-27001'&&<p className="text-xs text-ink-secondary">{definition.specification==='annex_control'?'This is an Annex A control. Record its risk-treatment selection and rationale in the Statement of Applicability below; selection alone does not demonstrate implementation.':'This is an ISMS requirement. Assess how the management system operates within scope; it is distinct from selecting Annex A controls in the Statement of Applicability.'}</p>}
    {framework==='nist-csf-2'&&<p className="text-xs text-ink-secondary">Assess the outcome in the current organizational scope, not a prescribed technology or artifact. Assessment notes describe current practice; use Profiles for the desired Target outcome and the explicit gap decision. A target is not evidence of current achievement.</p>}
    {framework==='soc-2'&&<p className="text-xs text-ink-secondary">The criterion describes an expectation. Management Controls describes how this organization addresses it. Assess control design and evidence of operation separately; neither creates an audit opinion. A policy or point-in-time screenshot may support design without demonstrating operation across the recorded observation period. Record coverage limits and exceptions in the assessment and control testing notes.</p>}
    <div className="border-b border-line pb-3"><h3 className="font-semibold">What to Review / Validate</h3><p className="mt-1">Typical validation may include: {guide.evidence}</p><p className="text-xs text-ink-secondary mt-2">Examples are not a mandatory artifact checklist. Consider scope, recency and actual operation; uploading a document does not prove compliance.</p></div>
    <div className="border-b border-line pb-3"><h3 className="font-semibold">Governance &amp; Recurrence{loading?'':` · ${related?.reviews?.length||0} linked Reviews`}</h3><p className="mt-2">Source activity: {REQUIREMENT_TYPES[definition.type]}. {definition.source_cadence}</p><p className="text-xs mt-2">{cadence.basis==='REQUIRED_EXPLICIT'?'Explicit source interval recorded for this requirement.':cadence.basis==='REQUIRED_ORG_DEFINED'?'Recurring activity; frequency is organization-defined.':cadence.basis==='RECOMMENDED'?'Review setup below is an operational recommendation, not a claim that this requirement prescribes that calendar interval.':'No recurring Review recommendation in this catalog. Operational and event-triggered duties still apply.'}</p>{plans.map(p=><div className="mt-3" key={p.key}><h4 className="font-medium">{p.title}</h4><p className="text-xs text-ink-secondary">{p.basis} · {p.source_cadence}</p><p className="mt-1">{p.reason}</p><p className="mt-1">Suggested setup cadence: {p.default_cadence}. The linked Review owns the actual schedule and completion evidence.</p></div>)}</div>
  </section>;
}
