import {operatorGuidance,operatorProgram} from '@/lib/frameworkOperator';
import {REQUIREMENT_TYPES,SPECIFICATION_LABELS} from '@/lib/frameworks';

export default function FrameworkContext({framework,definition,catalog,related,loading}){
  const guide=operatorGuidance(framework,definition),official=definition.source_type==='regulatory_text';
  const plans=catalog.review_plans.filter(p=>p.safeguards.includes(definition.id));
  return <section className="space-y-3 text-sm" aria-label="Requirement context">
    <div className="border-l-2 border-line-strong pl-3 text-xs text-ink-secondary"><p className="font-medium mb-1">{official?'Regulatory source':'Framework source reference'}</p><a className="text-link underline" href={definition.source} target="_blank" rel="noreferrer">Reference · {operatorProgram(framework)} · {definition.id}</a><span className="block mt-1">Version {catalog.version} · {definition.control_name}</span></div>
    {definition.specification&&<p className="text-xs font-medium text-ink-secondary">{SPECIFICATION_LABELS[definition.specification]}{definition.specification==='addressable'?' · Addressable does not mean optional. Record the decision and rationale below.':''}</p>}
    {official&&<details open={definition.guidance.length<700} className="border-b border-line pb-3"><summary className="cursor-pointer font-medium">Official requirement · regulatory text</summary><p className="mt-2 whitespace-pre-wrap">{definition.guidance}</p></details>}
    <div><h3 className="font-semibold">What this means</h3><p className="mt-1 whitespace-pre-wrap">{guide.meaning}</p><p className="mt-1 text-xs text-ink-secondary">Omnisciente guidance · {official?'Explanation, separate from the regulatory text.':'Summary, not verbatim framework text. Consult the reference for full wording and scope.'}</p></div>
    {framework==='iso-27001'&&<p className="text-xs text-ink-secondary">{definition.specification==='annex_control'?'This is an Annex A control. Record its risk-treatment selection and rationale in the Statement of Applicability below; selection alone does not demonstrate implementation.':'This is an ISMS requirement. Assess how the management system operates within scope; it is distinct from selecting Annex A controls in the Statement of Applicability.'}</p>}
    {framework==='nist-csf-2'&&<p className="text-xs text-ink-secondary">Assess the outcome in the current organizational scope, not a prescribed technology or artifact. Assessment notes describe current practice; use Profiles for the desired Target outcome and the explicit gap decision. A target is not evidence of current achievement.</p>}
    {framework==='soc-2'&&<p className="text-xs text-ink-secondary">The criterion describes an expectation. Management Controls describes how this organization addresses it. Assess control design and evidence of operation separately; neither creates an audit opinion. A policy or point-in-time screenshot may support design without demonstrating operation across the recorded observation period. Record coverage limits and exceptions in the assessment and control testing notes.</p>}
    <details className="border-b border-line pb-3"><summary className="cursor-pointer font-medium">Implementation guidance &amp; evidence examples</summary><h4 className="font-medium mt-3">Implementation guidance</h4><p className="mt-1">{guide.implementation}</p><h4 className="font-medium mt-3">Evidence examples</h4><p className="mt-1">{guide.evidence}</p><p className="text-xs text-ink-secondary mt-2">Examples are not a mandatory artifact checklist. Consider scope, recency and actual operation; a document or a reported practice alone may leave validation incomplete.</p></details>
    <details className="border-b border-line pb-3"><summary className="cursor-pointer font-medium">Governance &amp; recurrence{loading?'':` · ${related?.reviews?.length||0} linked Reviews`}</summary><p className="mt-2">Activity: {REQUIREMENT_TYPES[definition.type]}. {definition.source_cadence}</p>{plans.map(p=><div className="mt-3" key={p.key}><h4 className="font-medium">{p.title}</h4><p className="text-xs text-ink-secondary">{p.basis} · {p.source_cadence}</p><p className="mt-1">{p.reason}</p><p className="mt-1">Suggested setup cadence: {p.default_cadence}. The linked Review owns the actual schedule and completion evidence.</p></div>)}<p className="mt-2 text-xs text-ink-secondary">{plans.length?'Recommendations do not create work here. Open linked Reviews in Related to inspect the actual cadence, occurrence history and evidence.':'No recurring Review is recommended for this item by the current catalog. Assessment does not create a scheduled task.'}</p></details>
  </section>;
}
