import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import api,{formatError} from '@/lib/api';
import {Button} from './ui/button';
import ReviewDrawer from './ReviewDrawer';

const statusLabel=value=>String(value||'not recorded').replaceAll('_',' ');
const soaState=row=>row.soa_applicability==='excluded'?'Not Necessary':row.soa_applicability!=='included'?'Decision needed':row.status==='addressed'?'Necessary — Implemented':row.status==='not_assessed'?'Necessary — Not Implemented':'Necessary — Partially Implemented';
const Card=({title,value,detail,tone=''})=><article className="rounded-lg border border-line bg-surface-card p-4 space-y-1"><p className="text-xs text-ink-secondary">{title}</p><p className={'font-semibold '+(tone==='attention'?'text-semantic-warning':'')}>{value}</p><p className="text-xs text-ink-secondary">{detail}</p></article>;

export default function IsoProgramWorkspace({clientId,mode,rows}){
  const [data,setData]=useState({reviews:[],risks:[],findings:[],tasks:[],policies:[]}),[error,setError]=useState(''),[selected,setSelected]=useState(null),[revision,setRevision]=useState(0);
  useEffect(()=>{const c=new AbortController();setError('');Promise.all(['reviews','risks','findings','tasks','policies'].map(kind=>api.get('/'+kind,{params:{client_id:clientId},signal:c.signal}))).then(result=>{if(!c.signal.aborted)setData(Object.fromEntries(result.map((r,i)=>[['reviews','risks','findings','tasks','policies'][i],Array.isArray(r.data)?r.data:[]])));}).catch(e=>{if(!c.signal.aborted)setError(formatError(e));});return()=>c.abort();},[clientId,revision]);
  const clauses=rows.filter(r=>r.specification==='isms_clause'),annex=rows.filter(r=>r.specification==='annex_control'),audits=data.reviews.filter(r=>r.iso_audit),management=data.reviews.find(r=>(r.framework_drivers||[r]).some(d=>d.framework_plan_key==='iso-management-review')),objectives=data.reviews.flatMap(review=>(review.isms_objectives||[]).map(objective=>({review,objective})));
  const latestManagement=management?.occurrences?.at(-1),openFindings=data.findings.filter(f=>!f.closed_at&&f.status!=='closed'),openRisks=data.risks.filter(r=>!['closed'].includes(r.status)),significant=openRisks.filter(r=>(r.likelihood_score||0)*(r.impact_score||0)>=12),soa=useMemo(()=>annex.reduce((a,r)=>{a[soaState(r)]++;return a;},{'Necessary — Implemented':0,'Necessary — Partially Implemented':0,'Necessary — Not Implemented':0,'Not Necessary':0,'Decision needed':0}),[annex]);
  const drawer=selected&&<ReviewDrawer open record={selected} clientId={clientId} onOpenChange={open=>{if(!open){setSelected(null);setRevision(n=>n+1);}}} onSaved={()=>setRevision(n=>n+1)}/>;
  if(error)return <p role="alert" className="text-sm text-semantic-critical">ISO programme details could not be loaded. {error}</p>;
  if(mode==='overview')return <section className="space-y-4" aria-label="ISMS Overview">
    <div><h2 className="font-semibold">ISMS Overview</h2><p className="text-sm text-ink-secondary">Connected Year-2 operating view. Counts describe assessment and programme progress, not ISO compliance or certification.</p></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-3">
      <Card title="ISMS assessment" value={`${clauses.filter(r=>r.status!=='not_assessed').length} of ${clauses.length} requirements assessed`} detail={`${clauses.filter(r=>['needs_attention','in_progress'].includes(r.status)).length} need follow-up`}/>
      <Card title="Statement of Applicability" value={`${soa['Necessary — Implemented']} implemented`} detail={`${soa['Necessary — Partially Implemented']+soa['Necessary — Not Implemented']} unresolved · ${soa['Not Necessary']} Not Necessary · ${soa['Decision needed']} decision needed`} tone={soa['Decision needed']?'attention':''}/>
      <Card title="Annex A" value={`${annex.length} reference controls`} detail="Organizational · People · Physical · Technological"/>
      <Card title="Internal audit programme" value={`${audits.length} planned packages`} detail={`${audits.flatMap(r=>r.occurrences||[]).filter(o=>o.completed_at).length} completed audit occurrences retained`}/>
      <Card title="Management review" value={latestManagement?.completed_at?`Last held ${latestManagement.completed_at.slice(0,10)}`:'No completed occurrence'} detail={management?.due_date?`Next ${management.due_date.slice(0,10)} · Program Standard annual cadence`:'Needs scheduling'} tone={!latestManagement?'attention':''}/>
      <Card title="ISMS objectives" value={`${objectives.filter(({objective})=>objective.status==='on_track').length} of ${objectives.length} on track`} detail={`${objectives.filter(({objective})=>objective.status==='attention').length} require attention`}/>
      <Card title="Significant risks" value={`${significant.length} unresolved`} detail={`${openRisks.length} open or accepted Risks in the authoritative register`} tone={significant.length?'attention':''}/>
      <Card title="Corrective action" value={`${openFindings.length} open Findings`} detail={`${data.tasks.filter(t=>!['done','cancelled'].includes(t.status)).length} open Action Items`}/>
    </div>
    <div className="grid md:grid-cols-2 gap-3"><article className="rounded-lg border border-line bg-surface-card p-4"><h3 className="font-medium">Scope and context</h3><p className="text-sm mt-2">{clauses.find(r=>r.definition_id==='4.3')?.implementation||'Open Client Profile and Clause 4.3 for the approved scope.'}</p><div className="flex flex-wrap gap-2 mt-3"><Button asChild size="sm" variant="outline"><Link to="/client-profile">Client Profile</Link></Button><Button asChild size="sm" variant="outline"><Link to="/contacts">Contacts</Link></Button></div></article>
      <article className="rounded-lg border border-line bg-surface-card p-4"><h3 className="font-medium">Connected programme records</h3><p className="text-sm text-ink-secondary mt-2">Authoritative work stays in the shared modules; this workspace summarizes and links it.</p><div className="flex flex-wrap gap-2 mt-3">{[['/risks','Risks'],['/policies','Policies'],['/reviews','Reviews'],['/calendar','Calendar'],['/evidence','Evidence'],['/findings','Findings & Actions']].map(([to,label])=><Button asChild key={to} size="sm" variant="outline"><Link to={to}>{label}</Link></Button>)}</div></article></div>
  </section>;
  if(mode==='risk_treatment')return <section className="space-y-4" aria-label="Risk Assessment and Treatment"><div><h2 className="font-semibold">Risk Assessment &amp; Treatment</h2><p className="text-sm text-ink-secondary">The shared Risk register owns assessment and treatment. Control references connect treatment to implementation and SoA decisions.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b border-line"><th className="p-2">Risk</th><th className="p-2">Treatment</th><th className="p-2">Control references</th><th className="p-2">Status</th></tr></thead><tbody>{data.risks.map(r=><tr className="border-b border-line" key={r.risk_id}><td className="p-2"><span className="font-medium">{r.title}</span><span className="block text-xs text-ink-secondary">{r.treatment_reference||'Treatment reference not recorded'}</span></td><td className="p-2">{r.treatment}<span className="block text-xs text-ink-secondary">{r.treatment_plan}</span></td><td className="p-2">{r.control_refs?.join(' · ')||'Not mapped'}</td><td className="p-2 capitalize">{statusLabel(r.status)}</td></tr>)}</tbody></table></div><Button asChild><Link to="/risks">Open authoritative Risk register</Link></Button></section>;
  if(mode==='management_review')return <><section className="space-y-4" aria-label="Management Review"><div><h2 className="font-semibold">Management Review</h2><p className="text-sm text-ink-secondary">Scheduled and retained through Reviews. Annual is Dunder’s Program Standard, not an ISO-prescribed frequency.</p></div>{management?<><div className="grid md:grid-cols-2 gap-3"><Card title="Current schedule" value={management.due_date?.slice(0,10)||'Needs scheduling'} detail={`${management.recurrence||'No'} recurrence · ${management.occurrences?.length||0} prior occurrences`}/><Card title="Participants" value={`${management.participants?.length||0} recorded`} detail={management.participants?.join(' · ')||'Not recorded'}/></div><article className="rounded-lg border border-line bg-surface-card p-4"><h3 className="font-medium">Required inputs</h3><ul className="grid md:grid-cols-2 gap-2 mt-3">{management.management_review?.inputs.map(([label,state])=><li key={label} className="text-sm flex justify-between gap-2 border-b border-line py-1"><span>{label}</span><span className={state==='attention'?'text-semantic-warning':'text-ink-secondary'}>{state==='attention'?'Needs attention':'Included'}</span></li>)}</ul></article><div className="grid md:grid-cols-3 gap-3">{[['Decisions',management.management_review?.decisions],['Improvement opportunities',management.management_review?.improvements],['Required ISMS changes',management.management_review?.required_changes]].map(([title,items])=><article className="rounded-lg border border-line bg-surface-card p-4" key={title}><h3 className="font-medium">{title}</h3><ul className="list-disc pl-5 text-sm mt-2 space-y-1">{items?.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><Button onClick={()=>setSelected(management)}>Open central Review and history</Button></>:<p>No configured Management Review found.</p>}</section>{drawer}</>;
  if(mode==='objectives')return <><section className="space-y-4" aria-label="ISMS Objectives"><div><h2 className="font-semibold">ISMS Objectives</h2><p className="text-sm text-ink-secondary">Measurable outcomes with owners, targets, methods, results and recurring Review history. One-time remediation stays in Action Items.</p></div><div className="grid lg:grid-cols-2 gap-3">{objectives.map(({review,objective:o})=><article className="rounded-lg border border-line bg-surface-card p-4 space-y-2" key={o.key}><div className="flex justify-between gap-3"><h3 className="font-medium">{o.objective}</h3><span className={o.status==='attention'?'text-semantic-warning':'text-ink-secondary'}>{o.status==='attention'?'Needs attention':'On track'}</span></div><p className="text-sm"><span className="text-ink-secondary">Target:</span> {o.target}</p><p className="text-sm"><span className="text-ink-secondary">Measure:</span> {o.method}</p><p className="text-sm"><span className="text-ink-secondary">Current result:</span> {o.result}</p><p className="text-xs text-ink-secondary">{o.timeframe} · Owner recorded on objective · Next measurement {review.due_date?.slice(0,10)}</p><Button size="sm" variant="outline" onClick={()=>setSelected(review)}>Open Review history</Button></article>)}</div></section>{drawer}</>;
  return null;
}
