"""Loopback-only browser fixture: real auth/routes, synthetic in-memory Mongo.

Run explicitly, never imported by production. Credentials are generated by the
test caller and passed in the environment. No mail, external DB or IdP is used.
"""
import os
import sys
from pathlib import Path
from unittest.mock import patch, AsyncMock

from mongomock_motor import AsyncMongoMockClient
from starlette.responses import FileResponse
from starlette.staticfiles import StaticFiles
import uvicorn


if __name__ == '__main__':
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    os.environ.update(APP_ENV='test', MONGO_URL='mongodb://unused', DB_NAME='security_browser',
                      APP_BASE_URL='http://127.0.0.1:4190', CORS_ORIGINS='http://127.0.0.1:4190',
                      ADMIN_EMAIL='', ADMIN_PASSWORD_HASH='', RUN_LEGACY_MIGRATIONS='false', WEBHOOK_CRON_SECRET='')
    password = os.environ['SECURITY_TEST_PASSWORD']
    os.environ['JWT_SECRET']  # caller must supply an ephemeral secret
    with patch('dotenv.load_dotenv', return_value=False), patch('motor.motor_asyncio.AsyncIOMotorClient', AsyncMongoMockClient):
        import server
    server.send_email = AsyncMock(return_value=None)
    build = Path(os.environ['SECURITY_TEST_BUILD']).resolve()
    static = StaticFiles(directory=build)

    @server.app.on_event('startup')
    async def fixtures():
        password_hash = server.bcrypt.hashpw(password.encode(), server.bcrypt.gensalt()).decode()
        for uid, role, clients in [('owner','super_admin',['a','b']),('provider','platform_admin',['a']),
                ('manager','client_grc_manager',['a']),('contributor','client_contributor',['a']),
                ('reader','client_readonly',['a'])]:
            await server.db.users.insert_one(dict(user_id=uid, name=uid, email=uid+'@example.com',
                role=role, client_ids=clients, status='active', password_hash=password_hash))
        await server.db.clients.insert_many([dict(client_id=cid,name='Synthetic '+cid,status='active') for cid in ['a','b']])
        for cid in ['a','b']:
            await server.db.tasks.insert_one(dict(task_id='task-'+cid,client_id=cid,title='Synthetic activity',
                status='open',assignee_id='contributor',updated_at=None))

    async def application(scope, receive, send):
        if scope['type'] != 'http' or scope['path'].startswith('/api'):
            return await server.app(scope, receive, send)
        candidate = (build / scope['path'].lstrip('/')).resolve()
        if candidate.is_relative_to(build) and candidate.is_file():
            return await static(scope, receive, send)
        return await FileResponse(build/'index.html')(scope, receive, send)

    uvicorn.run(application, host='127.0.0.1', port=4190, log_level='info')
