import axios from 'axios';
import { previewAdapter } from './adapter';
import catalog from '@/lib/onboardingCatalog.json';
import { STORE_KEY } from './store';
const api=axios.create({adapter:previewAdapter});
const get=async(kind,cid)=>(await api.get(`/${kind}`,{params:{client_id:cid}})).data;
const state=()=>({version:2,step:3,policies:Object.fromEntries(catalog.policies.map((r,i)=>[r.key,['yes','no','unsure'][i%3]])),requirements:Object.fromEntries(catalog.requirements.map((r,i)=>[r.key,['applies','does_not_apply','unsure'][i%3]])),reviews:catalog.reviews.map(r=>r.key),completed:false});
beforeEach(async()=>{localStorage.clear();sessionStorage.clear();await api.post('/auth/login');});

test('revisiting intake preserves verified policy presence and its separate draft lifecycle', async () => {
  const client = (await api.post('/clients', { name: 'Verified policy QA' })).data;
  const s = state();
  await api.post('/onboarding/baseline', { client_id: client.client_id, state: s, finalize: true });
  const policy = (await get('policies', client.client_id))[0];
  await api.post(`/policies/${policy.policy_id}/verify`, { status: 'draft', version: '1.2' });
  await api.post('/onboarding/baseline', { client_id: client.client_id, state: s, finalize: true });
  expect((await get('policies', client.client_id)).find(p => p.policy_id === policy.policy_id)).toMatchObject({ presence: 'verified_existing', status: 'draft', version: '1.2' });
  expect(await get('policies', client.client_id)).toHaveLength(17);
});
test('focused catalog and new client defaults have exactly the requested content',async()=>{
  expect(catalog.policies).toHaveLength(17);expect(catalog.requirements).toHaveLength(5);expect(catalog.reviews).toHaveLength(17);
  const c=(await api.post('/clients',{name:'Baseline QA'})).data;
  const b=(await api.get('/onboarding/baseline',{params:{client_id:c.client_id}})).data;
  expect(b.state.reviews).toEqual(catalog.reviews.map(r=>r.key));
  expect(catalog.requirements.map(r=>r.name)).toEqual(['HIPAA','CIS Controls IG1','NIST Cybersecurity Framework 2.0','ISO/IEC 27001','Cybersecurity Maturity Model Certification (CMMC)']);
});
test('draft persistence, deselection, finalization, isolation and safe unscheduled reviews',async()=>{
  const a=(await api.post('/clients',{name:'A'})).data,b=(await api.post('/clients',{name:'B'})).data;
  const s=state();s.reviews=s.reviews.slice(1);
  await api.post('/onboarding/baseline',{client_id:a.client_id,state:s});
  const reloaded=axios.create({adapter:previewAdapter});
  expect((await reloaded.get('/onboarding/baseline',{params:{client_id:a.client_id}})).data.state.policies).toEqual(s.policies);
  expect((await reloaded.get('/onboarding/baseline',{params:{client_id:b.client_id}})).data.state.policies).not.toEqual(s.policies);
  await api.post('/onboarding/baseline',{client_id:a.client_id,state:s,finalize:true});
  expect(await get('policies',a.client_id)).toHaveLength(17);expect(await get('requirements',a.client_id)).toHaveLength(5);
  expect((await get('requirements',a.client_id)).find(r=>r.baseline_response==='does_not_apply').applicability).toBe('not_applicable');
  const reviews=await get('reviews',a.client_id);expect(reviews).toHaveLength(16);
  for(const r of reviews)expect(r).toMatchObject({status:'needs_scheduling',due_date:null,next_review_date:null,recurrence:null,owner_id:null});
  expect((await get('calendar',a.client_id))).toEqual({reviews:{},findings:{},tasks:{}});
  const summary=await get('dashboard',a.client_id);expect(summary.kpis.overdue_actions).toBe(0);expect(summary.kpis.due_next_30).toBe(0);
  expect(await get('reviews',b.client_id)).toEqual([]);expect(await get('tasks',a.client_id)).toEqual([]);expect(await get('risks',a.client_id)).toEqual([]);
  const manuallyEdited=reviews[0];
  await api.patch(`/reviews/${manuallyEdited.review_id}`,{title:'Manually renamed review',due_date:'2027-01-15',recurrence:'quarterly',notes:'Preserve review notes'});
  await api.post(`/reviews/${manuallyEdited.review_id}/complete`,{spawn_next:false,conclusion:'Practice reviewed',tested_period:'Q3 2026',tested_scope:'Scope documented',checklist_confirmed:true,no_evidence_reason:'Interview only'});
  const before=await get('reviews',a.client_id);
  await api.post('/onboarding/baseline',{client_id:a.client_id,state:s,finalize:true});
  expect(await get('policies',a.client_id)).toHaveLength(17);expect(await get('requirements',a.client_id)).toHaveLength(5);expect(await get('reviews',a.client_id)).toHaveLength(before.length);
  const kept=(await get('reviews',a.client_id)).find(r=>r.review_id===manuallyEdited.review_id);
  for(const k of ['title','status','due_date','completion_date','recurrence','owner_id','notes','evidence_ids'])expect(kept[k]).toEqual(before.find(r=>r.review_id===kept.review_id)[k]);
  const restored=(await api.get('/onboarding/baseline',{params:{client_id:a.client_id}})).data.state;
  expect(restored.completed).toBe(true);expect(restored.reviews).toEqual(s.reviews);expect(restored.requirements).toEqual(s.requirements);
});
test('invalid finalization is atomic; historical data and existing policy metadata survive',async()=>{
  const c=(await api.post('/clients',{name:'History'})).data;
  const policy = (await api.post('/policies',{client_id:c.client_id,title:'Information Security Policy',version:'3',onboarding_note:'Historical note'})).data;
  await api.post(`/policies/${policy.policy_id}/approve`,{});
  await api.post('/requirements',{client_id:c.client_id,title:'SOC 2',status:'active'});
  await api.post('/contacts',{client_id:c.client_id,name:'Existing Contact'});
  const original=sessionStorage.getItem(STORE_KEY),s=state();s.requirements.hipaa='invalid';
  await expect(api.post('/onboarding/baseline',{client_id:c.client_id,state:s,finalize:true})).rejects.toBeTruthy();
  expect(sessionStorage.getItem(STORE_KEY)).toBe(original);
  await api.post('/onboarding/baseline',{client_id:c.client_id,state:state(),finalize:true});
  expect(await get('policies',c.client_id)).toHaveLength(17);
  expect((await get('policies',c.client_id)).find(r=>r.title==='Information Security Policy')).toMatchObject({version:'3',status:'approved',onboarding_note:'Historical note'});
  expect((await get('requirements',c.client_id)).some(r=>r.title==='SOC 2')).toBe(true);
  expect(await get('contacts',c.client_id)).toHaveLength(1);
});

test('compliance navigation uses only finalized Applies selections and remains client scoped', async () => {
  const { complianceNavigation } = require('@/lib/complianceNavigation');
  const a = (await api.post('/clients', { name: 'Compliance A' })).data;
  const b = (await api.post('/clients', { name: 'Compliance B' })).data;
  const s = state();
  s.requirements = { hipaa: 'applies', 'cis-ig1': 'does_not_apply', 'nist-csf-2': 'unsure', 'iso-27001': 'applies', cmmc: 'applies' };
  const nav = async cid => complianceNavigation(cid, (await api.get('/onboarding/baseline', { params: { client_id: cid } })).data.state, await get('requirements', cid));
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s });
  expect(await nav(a.client_id)).toEqual([]);
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s, finalize: true });
  const initial = await nav(a.client_id);
  expect(initial.map(i => i.label)).toEqual(['HIPAA', 'ISO 27001', 'CMMC']);
  expect(initial.map(i => i.id)).toEqual(['hipaa', 'iso-27001', 'cmmc'].map(k => `${a.client_id}:${k}`));
  expect(await nav(b.client_id)).toEqual([]);
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s, finalize: true });
  expect(await nav(a.client_id)).toEqual(initial);
  s.requirements.hipaa = 'does_not_apply'; s.requirements.cmmc = 'unsure'; s.requirements['cis-ig1'] = 'applies';
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s });
  expect(await nav(a.client_id)).toEqual(initial);
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s, finalize: true });
  expect((await nav(a.client_id)).map(i => i.label)).toEqual(['CIS IG1', 'ISO 27001']);
  expect(await get('requirements', a.client_id)).toHaveLength(5);
  for (const k of Object.keys(s.requirements)) s.requirements[k] = 'unsure';
  await api.post('/onboarding/baseline', { client_id: a.client_id, state: s, finalize: true });
  expect(await nav(a.client_id)).toEqual([]);
});
