// DEMO - SYNTHETIC DATA. Brawndo is the reference program: deliberately imperfect.
// [status, days since last assessed (null = never), technology, current state, evidence age in days (null = none)]
// Assessment conclusions are fictional operator judgements, not assertions of compliance.
const A='addressed',P='in_progress',G='needs_attention',N='not_assessed';
export const BRAWNDO_CIS={
  '1.1':[G,40,'Intune device inventory; Entra ID device list','Intune covers corporate Windows and macOS laptops. Plant-floor tablets, BYOD mobile devices and network gear are not in any inventory, and no reconciliation against DHCP or EDR has been performed.',null],
  '1.2':[P,40,'EDR rogue-device reports','EDR flags unmanaged hosts on corporate VLANs, but alerts are reviewed ad hoc. No documented isolate/authorize decision or weekly cadence.',null],
  '2.1':[A,120,'Intune discovered apps; SaaS list in Vendor Register','Installed software exported quarterly from Intune. SaaS applications tracked against the Vendor Register by IT Lead.',110],
  '2.2':[P,120,'Intune discovered apps','Support status checked for major applications only. Two legacy label-printing applications are unsupported without a recorded exception.',null],
  '2.3':[A,120,'Intune app protection; standard user rights','Users lack local admin rights. Unauthorized installs surface in the monthly Intune report and are removed via ticket.',115],
  '3.1':[A,430,'Data Management Policy v2.0','Data Management Policy assigns data owners and handling requirements. Policy has not been reviewed since the ERP migration.',430],
  '3.2':[P,200,'SharePoint site inventory','Finance and HR repositories inventoried. Formulation (recipe) IP in the R&D file share is not yet inventoried.',null],
  '3.3':[A,95,'SharePoint and Entra ID groups','Sensitive sites restricted to role-based groups. External sharing disabled tenant-wide except for two approved partner sites.',95],
  '3.4':[A,410,'M365 retention policies','Retention labels configured in M365 for finance and HR records. Deletion execution not re-verified since configuration.',null],
  '3.5':[N,null,'','',null],
  '3.6':[A,60,'Intune BitLocker / FileVault policy','Encryption enforced by Intune compliance policy. Coverage report: 171 of 174 laptops encrypted; three exceptions on a replacement ticket.',55],
  '4.1':[P,150,'Intune security baselines','Windows security baseline deployed. macOS and server baselines are not documented.',null],
  '4.2':[G,150,'','Firewall and switch configurations are managed by a single network contractor with no documented standard or configuration backups.',null],
  '4.3':[A,60,'Intune device configuration profile','Screen lock at 10 minutes on Windows/macOS and 2 minutes on iOS, enforced by Intune.',60],
  '4.4':[A,300,'Windows Defender Firewall via GPO','Host firewall enabled on the four remaining on-premises servers. Rule review not repeated since the plant server was added.',300],
  '4.5':[A,60,'Intune endpoint security firewall policy','Host firewall enforced by Intune on all managed laptops. No disabled firewalls in the latest compliance report.',60],
  '4.6':[P,150,'','HTTPS management enabled on firewalls. Two plant switches still permit Telnet management.',null],
  '4.7':[N,null,'','',null],
  '5.1':[A,30,'Entra ID; quarterly HR reconciliation','Account inventory reconciled to HR roster each quarter by the Information Security Lead.',30],
  '5.2':[A,90,'Entra ID password policy; MFA','14-character minimum enforced in Entra ID with MFA. Shared plant-floor credentials retired in Q2.',90],
  '5.3':[G,30,'Entra ID sign-in logs','No process disables accounts after 45 days of inactivity. Latest sign-in export shows 23 enabled accounts inactive for more than 90 days.',null],
  '5.4':[P,30,'Entra ID admin roles','IT staff have separate admin accounts. The ERP vendor uses a standing Global Administrator account for support.',null],
  '6.1':[A,30,'ServiceDesk access request workflow','Access requests approved by manager in the service desk before provisioning. Sample of five new hires confirmed approval.',28],
  '6.2':[P,30,'HR offboarding checklist; Entra ID','Directory accounts disabled on the last day. SaaS applications outside SSO are revoked inconsistently (see open Finding).',null],
  '6.3':[A,45,'Entra ID Conditional Access','Conditional Access requires MFA for all users on all cloud apps. Legacy authentication blocked.',45],
  '6.4':[A,45,'VPN with Entra ID SAML and MFA','Remote VPN authenticates through Entra ID with MFA enforced.',45],
  '6.5':[A,45,'Entra ID Conditional Access; PIM','Admin roles require MFA and PIM activation. Two break-glass accounts documented and monitored.',45],
  '7.1':[A,380,'Managed vulnerability scanning','Vulnerability management procedure defines scan scope and severity timelines. Not reviewed in over a year.',380],
  '7.2':[P,60,'Managed vulnerability scanning; ticketing','Critical findings are remediated within timelines. High and medium findings lack tracked closure dates.',null],
  '7.3':[A,20,'Intune Windows Update rings; WSUS for servers','OS patching automated through Intune update rings. September compliance: 96% within 14 days.',20],
  '7.4':[P,20,'Intune (partial)','Browsers auto-update. Adobe, Java and plant HMI software are patched manually and irregularly.',null],
  '8.1':[N,null,'','',null],
  '8.2':[P,100,'M365 unified audit log; EDR telemetry','M365 and EDR logs collected. Firewall and ERP logs are not collected centrally.',null],
  '8.3':[A,420,'M365 audit retention','M365 audit log retention set to 180 days. Storage adequacy not reassessed since licence change.',null],
  '9.1':[A,90,'Intune managed Edge / Chrome','Only Edge and Chrome permitted, updated automatically. Outlook desktop kept on current channel.',90],
  '9.2':[A,90,'DNS filtering agent','DNS filtering applied on and off network through endpoint agent.',85],
  '10.1':[A,20,'Managed EDR','EDR deployed to 174 of 176 managed endpoints; two offline devices under investigation.',20],
  '10.2':[A,20,'Managed EDR','Engine and signature updates automatic; stale-definition report reviewed weekly by MSP.',20],
  '10.3':[N,null,'','',null],
  '11.1':[A,150,'Backup and recovery platform','Data recovery procedure defines priorities for ERP, file shares and M365. Recovery objectives not validated against plant operations.',150],
  '11.2':[A,20,'Backup and recovery platform','Nightly backups for servers and M365. Failed jobs alert to MSP; last restore test partially successful (see Risk).',20],
  '11.3':[A,150,'Backup platform encryption and RBAC','Backups encrypted; console access limited to two MSP engineers and the IT Lead.',null],
  '11.4':[G,150,'Backup and recovery platform','Backups replicate to a second region but in the same tenant with delete rights. No immutable or offline copy is verified.',null],
  '12.1':[P,150,'','Firewall firmware current. Two plant switches run end-of-life firmware with no replacement date.',null],
  '14.1':[A,480,'Annual awareness training platform','Awareness program owned by HR and Security. Last content review was before the current training vendor; completion not reported this year.',480],
  '14.2':[A,480,'Training platform; phishing simulation','Phishing module included in annual training. Simulations paused since vendor change.',null],
  '14.3':[A,480,'Training platform','Authentication module included in annual training.',null],
  '14.4':[A,480,'Training platform','Data handling module included in annual training.',null],
  '14.5':[N,null,'','',null],
  '14.6':[A,480,'Training platform','Incident recognition and reporting module included; reporting address matches current process.',null],
  '14.7':[N,null,'','',null],
  '14.8':[N,null,'','',null],
  '15.1':[A,70,'Vendor Register','Service provider inventory maintained in the Vendor Register with criticality and data classification.',70],
  '17.1':[A,200,'Incident Response Plan','Information Security Lead designated incident handler; IT Lead is backup.',200],
  '17.2':[G,400,'Incident Response Plan contact list','Contact list lists the former cyber insurer and MSP escalation numbers that changed in the spring.',null],
  '17.3':[A,200,'Incident Response Plan; intranet page','Reporting process published on the intranet and covered in training.',200],
};
// Findings raised from assessment gaps; Actions are the authoritative remediation.
// [safeguard, title, severity, action title, assignee index, action due (days), finding age]
export const BRAWNDO_CIS_FINDINGS=[
  ['1.1','Asset inventory excludes plant-floor, mobile and network devices','high','Extend inventory to all asset classes and reconcile against EDR and DHCP',2,-12,50],
  ['11.4','No isolated or immutable copy of recovery data','high','Configure immutable backup copy and verify isolation',2,-5,140],
  ['6.2','SaaS access not revoked consistently at termination','medium','Add non-SSO SaaS applications to offboarding checklist',0,21,28],
  ['7.4','Third-party application patching is manual and irregular','medium','Automate third-party application patching for managed endpoints',2,40,18],
  ['14.1','Awareness training completion not tracked for the current year','medium','Report training completion and follow up non-completers',1,-30,90],
];
