const {chromium}=require('playwright');
const {expect}=require('playwright/test');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 // Loopback only: synthetic QA activity never reaches an external service.
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.fulfill({status:204,body:''}));
 const base=process.env.CORE_QA_URL||'http://127.0.0.1:4174';
 if(new URL(base).hostname!=='127.0.0.1')throw new Error('Core QA requires an isolated local preview.');
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const go=path=>page.goto(base+path),db=()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('grc_interactive_demo_v3')));
 const review=()=>page.getByTestId('reviews-drawer').last(),pick=async(control,name)=>{await control.click();await page.getByRole('option',{name,exact:true}).click();};
 try{
  await go('/login');
  const bundle=await page.evaluate(async()=>{const src=[...document.scripts].map(s=>s.src).find(s=>s.includes('/static/js/main.'));const response=await fetch(src);if(!response.ok)throw Error('Bundle unavailable');const hash=await crypto.subtle.digest('SHA-256',await response.arrayBuffer());return {src,hash:Array.from(new Uint8Array(hash),v=>v.toString(16).padStart(2,'0')).join('')};});
  assert.ok(bundle.src.includes('/static/js/main.'),JSON.stringify(bundle));console.log('Verified baseline bundle:',bundle);
  await page.getByTestId('explore-demo').click();await page.waitForURL('**/clients');
  await go('/admin/clients');await page.getByTestId('add-client-button').click();await page.getByTestId('new-client-name').fill('Core workflow QA');await page.getByTestId('new-client-save').click();await expect(page.getByTestId('new-client-name')).toHaveCount(0);
  const cid=(await db()).clients.find(c=>c.name==='Core workflow QA').client_id;await page.evaluate(cid=>localStorage.setItem('grc_client_id',cid),cid);
  await page.evaluate(cid=>{const k='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(k));const analyst={user_id:'phase10-analyst',name:'Synthetic GRC Analyst',email:'analyst@example.test',role:'platform_admin',status:'active',client_ids:[cid]};d.users.push(analyst);d.user=analyst;sessionStorage.setItem(k,JSON.stringify(d));},cid);
  await go('/reviews');await page.getByTestId('create-reviews-button').click();await review().getByTestId('field-title').fill('Quarterly access audit');await pick(review().getByTestId('field-review_type'),'Access');await review().getByTestId('field-due_date').fill('2026-06-30');await pick(review().getByTestId('field-recurrence'),'Quarterly');await review().getByTestId('drawer-save').click();await expect(review().getByTestId('review-start')).toBeVisible();
  await review().getByTestId('review-start').click();await review().getByTestId('tab-evidence').click();await review().getByTestId('drawer-evidence-input').setInputFiles({name:'access-audit.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic access review evidence')});await expect(review()).toContainText('access-audit.txt');
  await review().getByTestId('tab-comments').click();await review().getByTestId('comment-input').fill('Reviewed privileged accounts.');await review().getByTestId('comment-submit').click();await expect(review()).toContainText('Reviewed privileged accounts.');
  await review().getByTestId('tab-overview').click();await review().getByTestId('quick-create-finding').click();await page.getByTestId('finding-title').fill('Privileged account ownership is incomplete');await page.getByTestId('finding-remediation-title').fill('Reconcile privileged account owners');await page.getByTestId('finding-save').click();await expect(page.getByTestId('review-finding-form')).toHaveCount(0);
  await review().getByTestId('review-complete').click();await expect(review().getByTestId('review-history')).toContainText('Q2 2026');await expect(review().getByTestId('field-due_date')).toHaveValue('2026-09-30');
  await review().getByTestId('tab-evidence').click();await expect(review()).toContainText('No Evidence is directly attached to this Review occurrence.');await expect(review()).toContainText('Direct Evidence (0)');await review().getByTestId('drawer-close').click();
  const adminId=(await db()).user.user_id;
  await page.evaluate(cid=>{const k='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(k));const auditor={user_id:'phase10-auditor',name:'Synthetic Auditor',email:'audit@example.test',role:'client_readonly',status:'active',client_ids:[cid]};d.users.push(auditor);d.user=auditor;sessionStorage.setItem(k,JSON.stringify(d));},cid);
  for(const [route,kind,title] of [['findings','findings','Privileged account ownership is incomplete'],['action-items','tasks','Reconcile privileged account owners']]){
   await go('/'+route);await page.getByText(title,{exact:true}).click();const source=page.getByTestId(kind+'-drawer');await source.getByTestId('tab-related').click();await expect(source).toContainText('Q2 2026');await source.getByRole('button',{name:'Quarterly access audit',exact:true}).click();await expect(review()).toContainText('Historical occurrence');await expect(review().getByTestId('review-period')).toHaveText('Q2 2026');await expect(review().getByTestId('review-complete')).toHaveCount(0);await review().getByTestId('tab-evidence').click();await expect(review()).toContainText('access-audit.txt');await review().getByTestId('drawer-close').click();await source.getByTestId('drawer-close').click();
  }
  await page.evaluate(id=>{const k='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(k));d.user=d.users.find(u=>u.user_id===id);sessionStorage.setItem(k,JSON.stringify(d));},adminId);
  await go('/findings');await page.getByText('Privileged account ownership is incomplete',{exact:true}).click();await page.getByTestId('findings-drawer').getByTestId('tab-related').click();await page.getByTestId('findings-drawer').getByRole('button',{name:'Reconcile privileged account owners',exact:true}).click();await page.getByTestId('tasks-drawer').getByRole('button',{name:'Complete Action Item',exact:true}).click();await expect(page.getByTestId('action-completion-handoff')).toContainText('awaiting validation');await page.getByTestId('tasks-drawer').getByRole('button',{name:'View Finding',exact:true}).click();await expect(page.getByTestId('findings-drawer').last().getByTestId('finding-validate')).toBeVisible();await go('/action-items');
  let data=await db();assert.equal(data.tasks.filter(t=>t.client_id===cid).length,1);assert.equal(data.findings.find(f=>f.client_id===cid).status,'remediated');assert.ok(data.tasks.find(t=>t.client_id===cid).completed_at);
  await expect(page.getByTestId('ai-view-active')).toContainText('0');
  await expect(page.locator('main')).not.toContainText('Reconcile privileged account owners');
  await page.getByTestId('ai-view-completed').click();await expect(page.locator('main')).toContainText('Reconcile privileged account owners');
  await go('/findings');await page.getByText('Privileged account ownership is incomplete',{exact:true}).click();await page.getByTestId('finding-validate').click();await page.getByRole('dialog').last().locator('textarea').fill('Validated named ownership against the supplied evidence.');await page.getByRole('button',{name:'Record decision',exact:true}).click();
  await go('/reviews');await page.getByText('Quarterly access audit',{exact:true}).click();await review().getByTestId('tab-related').click();
  await expect(review()).not.toContainText('Privileged account ownership is incomplete');await expect(review()).not.toContainText('Reconcile privileged account owners');
  await review().getByRole('button',{name:'Show completed / closed records (1)',exact:true}).click();
  await expect(review()).toContainText('Privileged account ownership is incomplete');await expect(review()).toContainText('Reconcile privileged account owners');
  await review().getByTestId('drawer-close').click();
  await go('/risks');await page.getByTestId('new-risk').click();await expect(page.getByTestId('new-risk-level')).toHaveText('Needs assessment');await page.getByTestId('new-risk-title').fill('Supplier concentration');await page.getByLabel('Risk description',{exact:true}).fill('Service delivery depends on a single supplier.');await pick(page.getByTestId('new-risk-likelihood'),'4 · Likely');await pick(page.getByTestId('new-risk-impact'),'4 · Major');await expect(page.getByTestId('new-risk-level')).toHaveText('critical');await page.getByTestId('new-risk-save').click();await expect(page.getByTestId('new-risk-dialog')).toHaveCount(0);
  data=await db();assert.equal(data.risks.find(r=>r.client_id===cid).risk_score,16);assert.equal(data.risks.find(r=>r.client_id===cid).status,'assessed');
  await page.getByText('Supplier concentration',{exact:true}).click();await page.getByLabel('Next Review',{exact:true}).fill('2026-09-20');await page.getByTestId('risks-drawer').getByTestId('drawer-save').click();
  data=await db();const risk=data.risks.find(r=>r.client_id===cid),riskReview=data.reviews.find(r=>r.risk_id===risk.risk_id);
  assert.ok(riskReview);await go('/calendar');await page.getByText(riskReview.title,{exact:true}).first().click();await expect(review()).toContainText('Risk reassessment');await review().getByTestId('review-complete').click();await expect(review().getByTestId('review-history')).toContainText('2026');await review().getByTestId('drawer-close').click();data=await db();assert.equal(data.risks.find(r=>r.risk_id===risk.risk_id).next_review.slice(0,10),'2027-09-20');assert.ok(data.risks.find(r=>r.risk_id===risk.risk_id).last_reviewed);
  await go('/risks');await page.getByText('Supplier concentration',{exact:true}).click();await page.getByTestId('risks-drawer').getByTestId('tab-treatment').click();await page.getByRole('button',{name:'Create Action Item',exact:true}).click();await page.getByTestId('tasks-drawer').getByTestId('field-title').fill('Evaluate alternate suppliers');await page.getByTestId('tasks-drawer').getByTestId('drawer-save').click();await expect(page.getByTestId('tasks-drawer')).toHaveCount(0);
  data=await db();const treatment=data.tasks.find(t=>t.title==='Evaluate alternate suppliers');assert.equal(treatment.source_type,'risk');assert.equal(treatment.source_id,risk.risk_id);
  await page.evaluate(cid=>{const k='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(k));const contributor={user_id:'phase10-contributor',name:'Synthetic IT Contributor',email:'it@example.test',role:'client_contributor',status:'active',client_ids:[cid]};d.users.push(contributor);d.user=contributor;sessionStorage.setItem(k,JSON.stringify(d));},cid);
  await go('/action-items');await page.getByText('Evaluate alternate suppliers',{exact:true}).click();await page.getByTestId('tasks-drawer').getByRole('button',{name:'Complete Action Item',exact:true}).click();await expect.poll(async()=>(await db()).tasks.find(t=>t.task_id===treatment.task_id).status).toBe('done');assert.notEqual((await db()).risks.find(r=>r.risk_id===risk.risk_id).status,'closed');
  await page.evaluate(id=>{const k='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(k));d.user=d.users.find(u=>u.user_id===id);sessionStorage.setItem(k,JSON.stringify(d));},adminId);
  await go('/vendors');await page.getByTestId('new-vendor').click();await page.getByTestId('new-vendor-name').fill('Audit service provider');await page.getByLabel('Service / Product *',{exact:true}).fill('Managed document storage');await page.getByLabel('Next Review date',{exact:true}).fill('2026-09-21');await page.getByTestId('new-vendor-save').click();await expect(page.getByTestId('new-vendor-dialog')).toHaveCount(0);
  data=await db();const vendor=data.vendors.find(v=>v.client_id===cid),vendorReview=data.reviews.find(r=>r.vendor_id===vendor.vendor_id);assert.ok(vendorReview);assert.equal(vendorReview.recurrence,'annual');await go('/reviews');await page.getByText(vendorReview.title,{exact:true}).click();await review().getByTestId('review-complete').click();await review().getByTestId('drawer-close').click();data=await db();assert.equal(data.vendors.find(v=>v.vendor_id===vendor.vendor_id).next_review.slice(0,10),'2027-09-21');assert.ok(data.vendors.find(v=>v.vendor_id===vendor.vendor_id).last_review);
  await go('/policies');await page.getByTestId('create-policies-button').click();await page.getByTestId('policies-drawer').getByTestId('field-title').fill('Audit security policy');await page.getByTestId('policies-drawer').getByTestId('drawer-save').click();await expect(page.getByTestId('policies-drawer')).toHaveCount(0);
  await go('/reviews');await page.getByTestId('create-reviews-button').click();await review().getByTestId('field-title').fill('Annual security policy review');await pick(review().getByTestId('field-review_type'),'Policy');await pick(review().getByTestId('field-policy_id'),'Audit security policy');await review().getByTestId('field-due_date').fill('2026-09-22');await pick(review().getByTestId('field-recurrence'),'Annual');await review().getByTestId('drawer-save').click();await expect(review().getByTestId('review-complete')).toBeVisible();await review().getByTestId('review-complete').click();await expect(review().getByTestId('field-due_date')).toHaveValue('2027-09-22');await review().getByTestId('drawer-close').click();data=await db();const policy=data.policies.find(p=>p.client_id===cid);assert.equal(policy.next_review_date.slice(0,10),'2027-09-22');assert.ok(policy.last_reviewed_at);assert.equal(policy.status,'draft');
  await page.evaluate(()=>{const key='grc_interactive_demo_v3',d=JSON.parse(sessionStorage.getItem(key));d.user=d.users.find(u=>u.role==='super_admin');sessionStorage.setItem(key,JSON.stringify(d));});await go('/clients');await page.getByTestId('sidebar-open-'+data.clients.find(c=>c.name==='Prestige Worldwide').client_id).click();await go('/reviews');await expect(page.locator('main')).not.toContainText('Quarterly access audit');await go('/findings');await expect(page.locator('main')).not.toContainText('Privileged account ownership is incomplete');
  assert.deepEqual(errors,[]);console.log('PASS core browser chain: Review create/start/evidence/comment/Finding+single Action/completion/calendar cadence; Finding and Action reopen Q2 history, fresh occurrence clean; Action completion, separate Finding validation; intentional Risk ratings and derived score; second-client exclusion.');
 }catch(e){if(process.env.QA_ARTIFACTS)await page.screenshot({path:require('node:path').join(process.env.QA_ARTIFACTS,'core-audit-failure.png'),fullPage:true});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
