import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
import RiskRegister from './RiskRegister';
import api from '@/lib/api';
let mockClient='demo_brawndo';
const mockUser={user_id:'admin',role:'super_admin',workspace_mode:'demo'};
jest.mock('@/context/AuthContext',()=>({useAuth:()=>({user:mockUser})}));
jest.mock('@/context/OrgContext',()=>({useOrg:()=>({currentClientId:mockClient,currentClient:{name:'Test client'}})}));
jest.mock('@/lib/api',()=>({__esModule:true,default:{get:jest.fn(),post:jest.fn()},formatError:e=>e.message,API:'/api'}));
jest.mock('react-router-dom',()=>({useLocation:()=>({pathname:'/risks',search:''}),useNavigate:()=>jest.fn(),useSearchParams:()=>require('react').useState(new URLSearchParams())}),{virtual:true});
jest.mock('@/components/RecordDrawer',()=>()=>null);
let root,container,rows;
const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text||b.textContent.startsWith(text));
const click=async node=>act(async()=>node.click());
beforeEach(()=>{
 global.IS_REACT_ACT_ENVIRONMENT=true;mockClient='demo_brawndo';localStorage.clear();
 container=document.createElement('div');document.body.appendChild(container);root=createRoot(container);
 rows=[{risk_id:'late',client_id:mockClient,title:'Late risk',status:'open',next_review:'2020-01-01',likelihood_score:3,impact_score:4},{risk_id:'undated',client_id:mockClient,title:'Undated risk',status:'open'},{risk_id:'closed',client_id:mockClient,title:'Closed risk',status:'closed'}];
 api.get.mockImplementation(async path=>({data:path==='/risks'?rows:[]}));
});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();jest.clearAllMocks();});
test('stable summaries, filters and client isolation',async()=>{
 await act(async()=>root.render(<RiskRegister/>));
 expect(button('All Open').textContent).toContain('2');expect(button('Overdue Reviews').textContent).toContain('1');
 await click(button('Overdue Reviews'));expect(container.querySelector('tbody').textContent).not.toContain('Undated risk');
 await act(async()=>{const input=container.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'missing');input.dispatchEvent(new Event('input',{bubbles:true}));});
 expect(button('All Open').textContent).toContain('2');
 mockClient='demo_other';rows=rows.map(r=>({...r,client_id:mockClient}));
 await act(async()=>root.render(<RiskRegister/>));
 expect(container.querySelector('[aria-label="Risk summaries"]')).toBeNull();
 expect(container.textContent).not.toContain('Assigned Owner');
 mockClient='demo_brawndo';rows=rows.map(r=>({...r,client_id:mockClient}));
 await act(async()=>root.render(<RiskRegister/>));expect(button('All Open').textContent).toContain('2');
});
test('new risk has annual/undecided defaults and protects an unfinished draft',async()=>{
 await act(async()=>root.render(<RiskRegister/>));await click(button('New Risk'));
 const dialog=document.querySelector('[role="dialog"]');
 expect(dialog.className).toContain('brawndo-cis-assessment');expect(dialog.textContent).toContain('Not Yet Decided');expect(dialog.textContent).toContain('Annual');
 await act(async()=>{const input=dialog.querySelector('input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,'Unsaved risk');input.dispatchEvent(new Event('input',{bubbles:true}));});
 await click([...dialog.querySelectorAll('button')].find(b=>b.textContent==='Cancel'));
 expect(document.querySelector('[role="alertdialog"]')).not.toBeNull();expect(api.post).not.toHaveBeenCalled();
});
