import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {useAuth} from '@/context/AuthContext';
import api,{formatError} from '@/lib/api';
import {frameworkCatalog,ASSESSMENT_STATUSES,REQUIREMENT_TYPES,SPECIFICATION_LABELS} from '@/lib/frameworks';
import {useTableControls,ColumnControl,TableFilterChips} from '@/components/TableControls';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import FrameworkDrawer from '@/components/FrameworkDrawer';

export default function FrameworkWorkspace({frameworkKey,clientId}){
  const {user}=useAuth(),[data,setData]=useState(null),[users,setUsers]=useState([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),[search,setSearch]=useState(''),[selected,setSelected]=useState(null);
  useEffect(()=>{const c=new AbortController();setData(null);setSelected(null);setSearch('');setError('');if(!clientId)return;Promise.all([api.get('/frameworks/'+frameworkKey,{params:{client_id:clientId},signal:c.signal}),api.get('/clients/'+clientId+'/members',{signal:c.signal})]).then(([r,m])=>{if(!c.signal.aborted){setData(r.data);setUsers(m.data);}}).catch(e=>{if(!c.signal.aborted)setError(formatError(e));});return()=>c.abort();},[frameworkKey,clientId,revision]);
  const catalog=frameworkCatalog(frameworkKey),isCis=frameworkKey==='cis-ig1',item=isCis?'Safeguard':'Requirement';
  const rows=useMemo(()=>data?.assessments.map(a=>({...data.definitions.find(d=>d.id===a.definition_id),...a})).filter(a=>a.client_id===clientId)||[],[data,clientId]);
  const columns=useMemo(()=>[{key:'definition_id',label:'ID',sortable:true},{key:'control_name',label:isCis?'Control':'Section',filter:true},{key:'title',label:item,sortable:true},{key:isCis?'type':'specification',label:isCis?'Requirement Type':'Specification',filter:true,labelValue:v=>(isCis?REQUIREMENT_TYPES:SPECIFICATION_LABELS)[v]},{key:'status',label:'Status',filter:true,labelValue:v=>ASSESSMENT_STATUSES[v]},{key:'owner_id',label:'Owner',filter:true,emptyLabel:'Unassigned',optionsOnly:true,options:users.map(u=>({value:u.user_id,label:u.name||u.email}))}], [users,isCis,item]);
  const table=useTableControls({columns,rows,module:'framework-'+frameworkKey,scope:clientId+':'+user?.user_id});
  if(error)return <p role="alert" className="text-sm">{error}</p>;
  if(!data)return <p role="status" className="text-sm text-ink-muted">Loading program workspace…</p>;
  if(!data.configured)return <section className="border border-line bg-surface-card rounded p-6 text-sm"><p>{data.selected?'Program selected for this client.':'Program not currently selected.'}</p><p className="text-ink-muted mt-2">Select Applies in Client Settings to initialize this program after onboarding. Existing records are not reset.</p><Link className="text-link underline" to="/client-settings">Configure in Client Settings</Link></section>;
  const visible=table.apply(rows.filter(r=>(r.definition_id+' '+r.title+' '+r.control_name).toLowerCase().includes(search.toLowerCase())));
  return <div className="space-y-5" data-testid={isCis?'cis-workspace':'framework-workspace'}>{!data.selected&&<p className="text-sm text-ink-muted">Historical program · This framework is no longer an active driver. Assessments and linked work are retained.</p>}<div className="grid grid-cols-2 lg:grid-cols-6 gap-3"><div className="border border-line rounded p-3 text-sm">{isCis?'Total IG1 Safeguards':'Assessment Requirements'}<strong className="block text-xl">{rows.length}</strong></div>{Object.entries(ASSESSMENT_STATUSES).map(([k,label])=><button key={k} className="text-left border border-line rounded p-3 text-sm" onClick={()=>table.setFilter('status',[k])}>{label}<strong className="block text-xl">{rows.filter(r=>r.status===k).length}</strong></button>)}</div><p className="text-xs text-ink-muted">{isCis?'CIS Controls v8.1 · IG1 only.':catalog.scope_note} Status reflects recorded assessment, not certification. No compliance percentage is inferred.</p><Input aria-label={`Search ${item.toLowerCase()}s`} placeholder={`Search ${item.toLowerCase()}s…`} value={search} onChange={e=>setSearch(e.target.value)}/><TableFilterChips table={table}/><div className="register-table-frame overflow-x-auto border border-line rounded"><table className="w-full text-sm"><thead className="bg-surface-subtle"><tr>{columns.map(c=><th key={c.key} className="p-3 text-left"><ColumnControl table={table} column={c}/></th>)}<th className="p-3 text-left">Related</th></tr></thead><tbody>{visible.map(r=><tr key={r.framework_assessment_id} className="border-t border-line" data-testid={`${item.toLowerCase()}-${r.definition_id}`}><td className="p-3 font-mono whitespace-nowrap">{r.definition_id}</td><td className="p-3 text-xs text-ink-muted">{r.control_name}</td><td className="p-3"><button className="text-link text-left" onClick={()=>setSelected(r)}>{r.title}</button></td><td className="p-3 text-xs">{isCis?REQUIREMENT_TYPES[r.type]:SPECIFICATION_LABELS[r.specification]}</td><td className="p-3 whitespace-nowrap">{ASSESSMENT_STATUSES[r.status]}</td><td className="p-3">{users.find(u=>u.user_id===r.owner_id)?.name||'Unassigned'}</td><td className="p-3"><button className="text-link" aria-label={`Open ${item.toLowerCase()} ${r.definition_id} relationships`} onClick={()=>setSelected(r)}>Open</button></td></tr>)}</tbody></table>{!visible.length&&<div className="p-6 text-sm">No {item.toLowerCase()}s match the current filters. <Button variant="ghost" onClick={()=>{table.clear();setSearch('');}}>Clear filters</Button></div>}</div>{selected&&<FrameworkDrawer key={clientId+':'+selected.framework_assessment_id} open record={selected} clientId={clientId} onOpenChange={v=>{if(!v){setSelected(null);setRevision(n=>n+1);}}}/>}</div>;
}
