// DEMO - SYNTHETIC DATA. Prestige Worldwide: fictional media-licensing SaaS company, SOC 2 program in year 2.
// Readiness conclusions below are internal operator judgements (internal readiness testing), not a CPA opinion
// or an assertion of compliance. A SOC report is an external event issued by an independent service auditor.
// Narrative timeline (days before seed date): readiness gap assessment ~600; remediation; Type 1 as-of ~400
// (Whitewater & Associates CPAs, fictional); first 6-month Type 2 period ended ~182 with 3 exceptions (since
// remediated); current 12-month Type 2 observation period runs 180 days ago to 185 days ahead. Confidentiality
// was added to scope ~30 days ago, so C1.1 and C1.2 are not yet assessed.
// People: 0 = Dale Doback (GRC manager), 1 = Robert Doback (governance), 2 = Brennan Huff (engineering).
const A = 'addressed', P = 'in_progress', G = 'needs_attention', N = 'not_assessed';
const OK = {design: 'adequate', operating: 'effective'};
const INTERNAL = ' Internal readiness testing, not an auditor opinion.';

// Management controls. Shared by id wherever the same real control supports several criteria.
// expected / collected = instance counts in the current period so far (period started 180 days ago).
const CONTROLS = {
  'GV-01': {name: 'Code of conduct and security policy acknowledgement at hire', owner: 1, frequency: 'per-event', ...OK, expected: 23, collected: 23,
    description: 'New hires e-sign the code of conduct, acceptable use and information security policies in the HR platform before system access is granted.',
    population_notes: 'All 23 joiners in the period from the HR platform hire report; all inspected.',
    testing_notes: 'Matched signed acknowledgement dates to start dates; all signed on or before day one.' + INTERNAL},
  'GV-02': {name: 'Quarterly security committee meeting', owner: 1, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'Robert Doback chairs a quarterly security committee (Dale, Brennan, vCISO) reviewing metrics, risks, open findings and audit status, with minutes and action items.',
    population_notes: 'Two quarterly meetings in the period; both minute sets obtained.',
    testing_notes: 'Inspected agendas, attendance and minutes; risk register and finding status were reviewed at each meeting.' + INTERNAL},
  'GV-03': {name: 'Annual owner-level review of the security program', owner: 1, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'The owners\' board receives an annual security and SOC program briefing from the vCISO independent of engineering, including prior-period exceptions.',
    population_notes: 'One annual briefing held in the period (day -120).',
    testing_notes: 'Inspected board pack and minutes recording discussion of first-period exceptions and budget approval.' + INTERNAL},
  'GV-04': {name: 'Annual review of org chart and security role descriptions', owner: 1, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'Security responsibilities for the GRC manager, engineering lead and vCISO are documented in role descriptions and the org chart, reviewed annually.',
    population_notes: 'One annual review completed in the period.',
    testing_notes: 'Inspected approved org chart and RACI; reporting lines match HR records.' + INTERNAL},
  'GV-05': {name: 'Quarterly control-owner accountability check-in', owner: 1, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'Each control owner confirms their controls operated and reports exceptions to the committee; overdue items are escalated to Robert Doback.',
    population_notes: 'Two quarterly check-ins; 3 owners each.',
    testing_notes: 'Inspected signed owner confirmations and escalation log.' + INTERNAL},
  'GV-06': {name: 'Annual policy review and approval', owner: 1, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'The security policy set (14 policies) is reviewed by the vCISO and approved by Robert Doback annually, then republished to staff.',
    population_notes: 'One annual review cycle in the period covering all 14 policies.',
    testing_notes: 'Inspected version history and approval records; all 14 policies approved at day -140.' + INTERNAL},
  'HR-01': {name: 'Background check before start date', owner: 1, frequency: 'per-event', ...OK, expected: 23, collected: 23,
    description: 'Alice Huff (HR) initiates a background check through the screening vendor for every hire; results are cleared before the start date.',
    population_notes: 'All 23 joiners from the HR hire report; all inspected.',
    testing_notes: 'Compared screening completion dates to start dates; all cleared before start.' + INTERNAL},
  'HR-02': {name: 'Annual security awareness training', owner: 1, frequency: 'annual', design: 'adequate', operating: 'gap', expected: 130, collected: 128,
    description: 'All staff complete annual security awareness and phishing training in the training platform; HR follows up non-completers at 30 days.',
    population_notes: 'All 130 active staff at campaign close, from the training platform export.',
    testing_notes: '128 of 130 completed; two engineers on extended leave have no completion or documented deferral.' + INTERNAL},
  'EX-01': {name: 'Customer status page notice for service incidents', owner: 0, frequency: 'per-event', ...OK, expected: 4, collected: 4,
    description: 'Customer-impacting incidents are posted to the public status page within 60 minutes with a closing notice and summary.',
    population_notes: 'All 4 customer-impacting incidents in the incident log.',
    testing_notes: 'Inspected status page history; all notices posted within 60 minutes.' + INTERNAL},
  'EX-02': {name: 'Annual review of customer-facing security commitments', owner: 1, frequency: 'annual', design: 'gap', operating: 'effective', expected: 1, collected: 1,
    description: 'The trust page, MSA security exhibit and SLA terms are reviewed annually against actual controls.',
    population_notes: 'One review completed at day -150, before confidentiality was added to scope.',
    testing_notes: 'Review performed, but the trust page and security exhibit do not yet describe confidentiality commitments now in scope.' + INTERNAL},
  'RK-01': {name: 'Annual risk assessment', owner: 0, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'Dale Doback and the vCISO run an annual risk assessment against platform objectives (99.9% SLA, licensing data integrity, customer confidentiality) and update the risk register.',
    population_notes: 'One annual assessment completed at day -110.',
    testing_notes: 'Inspected assessment workbook, scoring and executive sign-off.' + INTERNAL},
  'RK-02': {name: 'Quarterly risk register review', owner: 0, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'Risk owners re-score risks and update treatment plans quarterly; results are presented at the security committee.',
    population_notes: 'Two quarterly reviews in the period.',
    testing_notes: 'Inspected register change history and committee minutes for both quarters.' + INTERNAL},
  'RK-03': {name: 'Annual fraud and misuse risk workshop', owner: 0, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'Finance (Nancy Huff), engineering and GRC review fraud scenarios such as royalty-report manipulation, fake licensee accounts and payout redirection.',
    population_notes: 'One workshop held at day -105.',
    testing_notes: 'Inspected workshop notes and the resulting register entries.' + INTERNAL},
  'RK-04': {name: 'Risk review for significant changes', owner: 0, frequency: 'per-event', design: 'adequate', operating: 'gap', expected: 2, collected: 1,
    description: 'Significant changes (new regions, major vendors, scope changes) require a documented risk review before go-live.',
    population_notes: 'Two significant changes identified in the period: CDN provider switch and confidentiality scope addition.',
    testing_notes: 'CDN switch review documented; the confidentiality scope addition has no recorded risk review yet.' + INTERNAL},
  'MON-01': {name: 'Monthly security metrics report to leadership', owner: 0, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Dale Doback issues a monthly report covering vulnerability SLA, access review status, alert volumes, training and open findings.',
    population_notes: 'Six monthly reports in the period.',
    testing_notes: 'Inspected all six reports; figures traced to source tooling for two months.' + INTERNAL},
  'MON-02': {name: 'Quarterly internal readiness control testing', owner: 0, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'The vCISO samples control evidence each quarter against the control matrix and records exceptions as findings.',
    population_notes: 'Two quarterly testing cycles in the period.',
    testing_notes: 'Inspected test worksheets; the exceptions raised match the open findings list.' + INTERNAL},
  'MON-03': {name: 'Monthly deficiency tracking to closure', owner: 0, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Open findings are reviewed monthly in the GRC platform with owners, due dates and validation evidence before closure.',
    population_notes: 'Six monthly reviews; all findings open at any point in the period.',
    testing_notes: 'Inspected review log; the three prior-period exceptions were closed with validation evidence.' + INTERNAL},
  'MON-04': {name: 'Annual control-to-risk mapping review', owner: 0, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'The control matrix is mapped to register risks annually to confirm each high risk has at least one operating control.',
    population_notes: 'One mapping review after the annual risk assessment.',
    testing_notes: 'Inspected mapping; every risk scored 12 or above maps to an operating control.' + INTERNAL},
  'MON-05': {name: 'Weekly SIEM alert triage review', owner: 0, frequency: 'weekly', design: 'adequate', operating: 'gap', expected: 26, collected: 24,
    description: 'Dale Doback and the MSP SOC review the weekly queue of SIEM and EDR alerts, confirm disposition and sign off the weekly review record.',
    population_notes: 'All 26 weeks in the period from the review log.',
    testing_notes: 'Sign-off missing for 2 weeks (holiday weeks); no evidence the queue was reviewed those weeks.' + INTERNAL},
  'MON-06': {name: 'Monthly log-source health check', owner: 0, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Production, identity-provider and cloud audit log sources are confirmed reporting to the SIEM with 365-day retention.',
    population_notes: 'Six monthly checks in the period.',
    testing_notes: 'Inspected health-check screenshots; no silent sources exceeded 24 hours.' + INTERNAL},
  'PT-01': {name: 'Annual external penetration test', owner: 2, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'Castle Rock Security Testing (fictional) tests the licensing web app, public APIs and cloud perimeter annually; findings are tracked to remediation.',
    population_notes: 'One test in the period (day -95).',
    testing_notes: 'Inspected report and retest letter; 1 high and 3 medium findings remediated and retested.' + INTERNAL},
  'TC-01': {name: 'Monthly cloud configuration posture review', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Infrastructure is managed as code; the monthly posture report (public storage, open security groups, unencrypted volumes) is reviewed and drift corrected.',
    population_notes: 'Six monthly reports in the period.',
    testing_notes: 'Inspected reports and linked tickets; no public storage buckets outstanding.' + INTERNAL},
  'AC-01': {name: 'SSO with enforced MFA for corporate and production access', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'All workforce apps and the cloud console authenticate through SSO with phishing-resistant MFA; a monthly report confirms no MFA-exempt accounts.',
    population_notes: 'Six monthly MFA coverage reports.',
    testing_notes: 'Inspected reports; the two documented break-glass accounts are vaulted and alert on use.' + INTERNAL},
  'AC-02': {name: 'Quarterly user access review', owner: 2, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'System owners review access to the cloud console, production database, code repository and admin panel each quarter; removals are ticketed.',
    population_notes: 'Two quarterly reviews covering 4 in-scope systems each.',
    testing_notes: 'Inspected sign-offs and removal tickets; all removals completed within 5 days.' + INTERNAL},
  'AC-03': {name: 'Joiner access provisioning with manager approval', owner: 2, frequency: 'per-event', ...OK, expected: 23, collected: 23,
    description: 'Access is granted from HR-triggered tickets with manager approval and role-based groups; production access needs separate engineering-lead approval.',
    population_notes: 'All 23 joiners from the HR report; all tickets inspected.',
    testing_notes: 'Approval preceded provisioning in all 23 tickets.' + INTERNAL},
  'AC-04': {name: 'Leaver access revocation within one business day', owner: 2, frequency: 'per-event', design: 'adequate', operating: 'gap', expected: 17, collected: 17,
    description: 'HR termination triggers SSO disablement and a checklist for non-SSO systems, to be completed within one business day.',
    population_notes: 'All 17 leavers from the HR termination report; all inspected.',
    testing_notes: 'Evidence exists for all 17, but one contractor\'s production database account was disabled 6 business days late.' + INTERNAL},
  'PH-01': {name: 'Quarterly office badge access review', owner: 2, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'Badge access to the single office and network closet is reviewed quarterly; data center physical security is carved out to the cloud provider.',
    population_notes: 'Two quarterly reviews of the badge system export.',
    testing_notes: 'Inspected reviews; badges for leavers were deactivated.' + INTERNAL},
  'AS-01': {name: 'Laptop retirement with certified wipe', owner: 2, frequency: 'per-event', design: 'adequate', operating: 'gap', expected: 9, collected: 8,
    description: 'Retired laptops are remotely wiped through MDM and sent to an ITAD provider that returns a wipe certificate per serial number.',
    population_notes: 'All 9 laptops retired in the period from the MDM retirement report.',
    testing_notes: '8 of 9 wipe certificates on file; one certificate not yet received from the ITAD provider.' + INTERNAL},
  'NW-01': {name: 'Quarterly network security group and WAF rule review', owner: 2, frequency: 'quarterly', ...OK, expected: 2, collected: 2,
    description: 'Inbound rules, WAF policies and exposed endpoints are reviewed quarterly against the approved exposure list.',
    population_notes: 'Two quarterly reviews.',
    testing_notes: 'Inspected rule exports and sign-offs; two stale rules removed in the second quarter.' + INTERNAL},
  'DP-01': {name: 'Monthly TLS and certificate configuration scan', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'External endpoints are scanned monthly to confirm TLS 1.2+ and valid certificates; customer file delivery uses signed, expiring URLs.',
    population_notes: 'Six monthly scans of all public hostnames.',
    testing_notes: 'Inspected scan output; no weak protocols found.' + INTERNAL},
  'DP-02': {name: 'Monthly MDM compliance report (encryption, removable media)', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'MDM enforces disk encryption and blocks removable storage on laptops; non-compliant devices lose SSO access.',
    population_notes: 'Six monthly compliance reports covering all managed laptops.',
    testing_notes: 'Inspected reports; non-compliant devices were remediated or blocked within 7 days.' + INTERNAL},
  'EP-01': {name: 'Monthly EDR coverage check', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'EDR runs on all laptops and production hosts; coverage is reconciled monthly against MDM and cloud inventory.',
    population_notes: 'Six monthly reconciliations.',
    testing_notes: 'Inspected reconciliations; gaps were new hosts enrolled within 48 hours.' + INTERNAL},
  'VU-01': {name: 'Monthly vulnerability scanning with remediation SLAs', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Hosts, containers and dependencies are scanned monthly; critical fixes due in 15 days and high in 30, tracked in engineering tickets.',
    population_notes: 'Six monthly scan cycles.',
    testing_notes: 'Inspected scan reports and ticket closure dates; no SLA breaches for critical or high.' + INTERNAL},
  'IR-01': {name: 'Security event triage and severity classification', owner: 0, frequency: 'per-event', ...OK, expected: 11, collected: 11,
    description: 'Escalated security events are logged, assigned a severity under the IR plan and tracked to disposition by Dale Doback.',
    population_notes: 'All 11 escalated events in the incident log.',
    testing_notes: 'Inspected tickets; severity, timeline and disposition recorded for all 11.' + INTERNAL},
  'IR-02': {name: 'Annual incident response tabletop', owner: 0, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'An annual tabletop exercises the IR plan with engineering, leadership, contracts (Nancy Huff) and the MSP SOC.',
    population_notes: 'One tabletop (ransomware on build pipeline) held at day -70.',
    testing_notes: 'Inspected attendance, after-action report and resulting plan updates.' + INTERNAL},
  'IR-03': {name: 'Post-incident review for Sev1 and Sev2 incidents', owner: 0, frequency: 'per-event', ...OK, expected: 2, collected: 2,
    description: 'Sev1/Sev2 incidents get a blameless post-incident review with root cause, recovery confirmation and tracked follow-ups.',
    population_notes: 'Both Sev2 incidents in the period; no Sev1.',
    testing_notes: 'Inspected both reviews; follow-up tickets closed.' + INTERNAL},
  'CH-01': {name: 'Peer-reviewed pull request approval before deploy', owner: 2, frequency: 'per-event', ...OK, expected: 410, collected: 410,
    description: 'Branch protection requires one approving reviewer other than the author and passing CI before merge to main, which is the only path to production.',
    population_notes: '410 production merges from the repository API; 40 sampled.',
    testing_notes: 'All 40 samples had an independent approval and green CI; branch protection settings confirmed monthly.' + INTERNAL},
  'CH-02': {name: 'Emergency change retro-approval within two business days', owner: 2, frequency: 'per-event', design: 'adequate', operating: 'gap', expected: 3, collected: 2,
    description: 'Emergency fixes deployed by break-glass merge must be retro-approved by the engineering lead within two business days.',
    population_notes: 'All 3 break-glass merges flagged by the repository audit log.',
    testing_notes: 'Two retro-approved on time; one hotfix (day -44) has no retro-approval.' + INTERNAL},
  'BC-01': {name: 'Annual business continuity plan review', owner: 1, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'The BCP (key-person cover, alternate vendors, cyber insurance with Nancy Huff) is reviewed and approved annually.',
    population_notes: 'One annual review completed at day -130.',
    testing_notes: 'Inspected approved BCP and change log.' + INTERNAL},
  'DR-01': {name: 'Annual disaster recovery failover test', owner: 2, frequency: 'annual', ...OK, expected: 1, collected: 1,
    description: 'The platform is failed over to the secondary cloud region annually and recovery time is measured against the 4-hour RTO.',
    population_notes: 'One failover test at day -80.',
    testing_notes: 'Inspected test report: recovery in 2h40m, within RTO.' + INTERNAL},
  'VM-01': {name: 'Vendor onboarding security review', owner: 0, frequency: 'per-event', ...OK, expected: 2, collected: 2,
    description: 'New vendors handling customer or employee data get a security review and contract clause check (Derek Huff, Nancy Huff) before signature.',
    population_notes: 'Both new data-handling vendors onboarded in the period.',
    testing_notes: 'Inspected review questionnaires and signed DPAs.' + INTERNAL},
  'VM-02': {name: 'Annual review of critical vendor SOC reports', owner: 0, frequency: 'annual', ...OK, expected: 3, collected: 3,
    description: 'SOC reports for the cloud host (carved-out subservice organization), payment processor and collaboration suite are reviewed annually, including complementary user entity controls.',
    population_notes: 'Three critical vendors requiring SOC reports.',
    testing_notes: 'Inspected review memos; CUEC mapping to Prestige controls completed for the cloud host.' + INTERNAL},
  'VM-03': {name: 'Bridge letters for SOC report coverage gaps', owner: 0, frequency: 'per-event', design: 'adequate', operating: 'gap', expected: 2, collected: 1,
    description: 'Where a vendor SOC report period ends more than 3 months before our period end, a bridge letter is obtained.',
    population_notes: 'Two vendors with coverage gaps (payment processor, collaboration suite).',
    testing_notes: 'Collaboration suite letter on file; the payment processor bridge letter is overdue.' + INTERNAL},
  'CP-01': {name: 'Monthly capacity and performance review', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'Engineering reviews CPU, storage, queue depth and media-transcode capacity monthly against forecast and adjusts autoscaling limits.',
    population_notes: 'Six monthly reviews.',
    testing_notes: 'Inspected dashboards and tickets; storage quota raised ahead of a catalog migration.' + INTERNAL},
  'CP-02': {name: 'Monthly uptime report against 99.9% SLA', owner: 2, frequency: 'monthly', ...OK, expected: 6, collected: 6,
    description: 'External synthetic monitoring measures availability; a monthly report compares uptime to the 99.9% commitment.',
    population_notes: 'Six monthly uptime reports.',
    testing_notes: 'Inspected reports; lowest month 99.93%.' + INTERNAL},
  'BK-01': {name: 'Daily automated backups with failure alerting', owner: 2, frequency: 'daily', ...OK, expected: 180, collected: 180,
    description: 'Production databases and the licensing metadata store are snapshotted daily to a separate account with immutability; failures page on-call.',
    population_notes: '180 daily backup job records from the backup console; 25 sampled.',
    testing_notes: 'All sampled jobs succeeded or were re-run the same day with alert evidence.' + INTERNAL},
  'BK-02': {name: 'Quarterly backup restore test', owner: 2, frequency: 'quarterly', design: 'adequate', operating: 'gap', expected: 2, collected: 1,
    description: 'A production database backup is restored to an isolated environment each quarter and integrity-checked against record counts.',
    population_notes: 'Two quarters in the period.',
    testing_notes: 'Q1 restore documented; no restore test performed in Q2.' + INTERNAL},
  'CF-01': {name: 'Confidential data classification and handling', owner: 0, frequency: 'annual', design: 'not_assessed', operating: 'not_assessed', expected: null, collected: null,
    description: 'Customer contracts, unreleased media and licensing terms are classified Confidential with storage, sharing and retention rules.',
    population_notes: 'Not yet defined; confidentiality added to scope ~30 days ago.',
    testing_notes: 'Not yet tested.'},
  'CF-02': {name: 'Customer data deletion at contract end', owner: 2, frequency: 'per-event', design: 'not_assessed', operating: 'not_assessed', expected: null, collected: null,
    description: 'Customer content and metadata are purged within 30 days of contract termination with a deletion confirmation.',
    population_notes: 'Not yet defined; population will be terminated customer contracts.',
    testing_notes: 'Not yet tested.'},
};
const ctl = (...ids) => ids.map(control_id => ({control_id, ...CONTROLS[control_id]}));
const row = (status, assessed_ago, owner, technology, narrative, evidence_ago, controls) =>
  ({status, assessed_ago, owner, technology, narrative, evidence_ago, controls});

const prestige = {
  framework: 'soc-2',
  soc: {
    categories: ['security', 'availability', 'confidentiality'],
    system_description: 'Prestige Worldwide Licensing Platform: a multi-tenant SaaS application that lets broadcasters and agencies search, license and download media assets, with rights metadata, contract terms and royalty reporting. Customer commitment: 99.9% monthly availability. In the boundary: the web app and public APIs, licensing metadata and customer file stores, CI/CD pipeline, identity provider, SIEM and backup tooling, and the people and processes that run them. Out of the boundary: the public cloud provider (carved-out subservice organization; physical and infrastructure controls rely on its SOC report), the payment processor, corporate finance systems and the marketing website.',
    period_start_ago: 180,
    period_end_in: 185,
  },
  profile: {
    organization: {
      employees: 130,
      technology_users: 130,
      locations: 1,
      workforce: 'Primarily remote',
      business_model: ['B2B'],
      it_management: ['Internal IT', 'MSP'],
      notes: 'DEMO - SYNTHETIC DATA. SOC 2 service organization (Security, Availability, Confidentiality); year-2 program with an MSP vCISO. Fictional role adaptations, not assertions about source characters.',
    },
    technical: {
      cloud: ['Other cloud'],
      infrastructure: ['Cloud servers', 'SaaS-first'],
      endpoints: ['macOS', 'Windows', 'Linux', 'iOS'],
      operating_environment: ['SaaS applications', 'Custom software development', 'Product development', 'Public-facing applications'],
      security_technology: ['EDR/XDR', 'SIEM', 'MFA', 'IAM', 'Backup', 'MDM', 'Vulnerability management', 'Email security', 'Security awareness'],
    },
    security: {
      data_types: ['Customer confidential information', 'PII', 'Intellectual property', 'Source code', 'Employee information'],
      hosts: 'Yes',
      develops: 'Yes',
      secure_development: 'Implemented',
    },
  },
  assessments: {
    'CC1.1': row(A, 60, 1, 'HR platform; code of conduct', 'Code of conduct and security policies are e-signed at hire, and every hire is background-checked before start. Violations route to Robert Doback and HR.', 45, ctl('GV-01', 'HR-01')),
    'CC1.2': row(A, 90, 1, 'Board pack; committee minutes', 'The owners\' board gets an annual program briefing from the vCISO, separate from engineering, and the quarterly security committee minutes are shared with it.', 120, ctl('GV-03', 'GV-02')),
    'CC1.3': row(A, 120, 1, 'Org chart; RACI', 'Security roles for Dale (GRC), Brennan (engineering) and the MSP vCISO are defined in role descriptions and a RACI, reviewed annually.', 125, ctl('GV-04')),
    'CC1.4': row(P, 30, 1, 'HR platform; screening vendor; training platform', 'All 23 hires were background-checked before start. Annual training reached 128 of 130 staff; two engineers on leave have no completion or recorded deferral.', 28, ctl('HR-01', 'HR-02')),
    'CC1.5': row(A, 60, 1, 'GRC platform; committee minutes', 'Control owners confirm operation quarterly and overdue items escalate to Robert Doback at the security committee.', 50, ctl('GV-05', 'GV-02')),
    'CC2.1': row(A, 45, 0, 'SIEM; scanner; GRC platform', 'Dale produces a monthly metrics report from source tools (scanner, IdP, SIEM, training platform) and the committee reviews it quarterly.', 20, ctl('MON-01', 'GV-02')),
    'CC2.2': row(A, 140, 1, 'Policy portal; HR platform', 'Policies are republished after the annual review and acknowledged by every hire; changes are announced in the all-hands channel.', 140, ctl('GV-06', 'GV-01')),
    'CC2.3': row(P, 40, 1, 'Status page; trust page; MSA exhibit', 'Incidents reach customers through the status page within 60 minutes. The trust page and security exhibit have not been updated for confidentiality commitments added to scope.', 35, ctl('EX-01', 'EX-02')),
    'CC3.1': row(A, 110, 0, 'Risk register', 'Risk objectives are tied to platform commitments (99.9% SLA, licensing data integrity, customer confidentiality) in the annual risk assessment.', 110, ctl('RK-01', 'GV-02')),
    'CC3.2': row(A, 110, 0, 'Risk register', 'Risks are scored annually and re-scored quarterly by owners, with treatment plans tracked in the register.', 60, ctl('RK-01', 'RK-02')),
    'CC3.3': row(A, 105, 0, 'Risk register; finance controls', 'A yearly workshop with Nancy Huff (finance) covers royalty-report tampering, fake licensee accounts and payout redirection.', 105, ctl('RK-03', 'RK-01')),
    'CC3.4': row(P, 25, 0, 'Change calendar; risk register', 'The CDN provider switch had a documented risk review. Adding confidentiality to scope has no recorded risk review yet.', null, ctl('RK-04', 'RK-02')),
    'CC4.1': row(A, 30, 0, 'GRC platform; pen test report', 'The vCISO tests control samples every quarter, and Castle Rock Security Testing (fictional) runs an annual external pen test.', 30, ctl('MON-02', 'PT-01')),
    'CC4.2': row(A, 30, 0, 'GRC platform', 'Findings are tracked monthly to validated closure. All three first-period exceptions were closed with evidence 60-90 days ago.', 30, ctl('MON-03', 'GV-02')),
    'CC5.1': row(A, 100, 0, 'Control matrix', 'Every risk scored 12 or higher maps to at least one operating control. The mapping is checked after each annual risk assessment.', 100, ctl('MON-04', 'RK-01')),
    'CC5.2': row(A, 35, 2, 'Infrastructure as code; posture scanner', 'Infrastructure is defined in code with a monthly posture review for drift. Access to systems is recertified quarterly.', 15, ctl('TC-01', 'AC-02')),
    'CC5.3': row(A, 140, 1, 'Policy portal', 'Procedures sit under the approved policy set, and each policy lists the controls that put it into practice. Hires acknowledge policies before getting access.', 140, ctl('GV-06', 'GV-01')),
    'CC6.1': row(A, 20, 2, 'SSO; MFA; IdP', 'All workforce and cloud console access goes through SSO with phishing-resistant MFA. Access to the four in-scope systems is reviewed quarterly.', 15, ctl('AC-01', 'AC-02')),
    'CC6.2': row(A, 20, 2, 'Ticketing; IdP groups', 'HR-triggered tickets with manager approval drive provisioning; production access requires Brennan\'s separate approval.', 22, ctl('AC-03', 'AC-02')),
    'CC6.3': row(G, 20, 2, 'IdP; offboarding checklist', 'SSO is disabled at termination, but one contractor\'s production database account was removed 6 business days late. This repeats a first-period exception.', 20, ctl('AC-04', 'AC-02')),
    'CC6.4': row(A, 60, 2, 'Badge system; cloud SOC report', 'Only the office and network closet are in scope and badge access is reviewed quarterly. Data center controls are carved out to the cloud provider\'s SOC report.', 60, ctl('PH-01', 'VM-02')),
    'CC6.5': row(P, 30, 2, 'MDM; ITAD provider', 'Retired laptops are wiped through MDM and certified by the ITAD provider. One of nine certificates is still outstanding.', 30, ctl('AS-01')),
    'CC6.6': row(A, 50, 2, 'WAF; security groups', 'Inbound exposure is limited to the load balancer and API gateway behind a WAF, and rules are reviewed quarterly. The annual pen test covers the perimeter.', 50, ctl('NW-01', 'PT-01')),
    'CC6.7': row(A, 40, 2, 'TLS scanner; MDM', 'External endpoints enforce TLS 1.2+, and customer downloads use signed, expiring URLs. Laptops block removable storage.', 12, ctl('DP-01', 'DP-02')),
    'CC6.8': row(A, 40, 2, 'EDR; MDM', 'EDR runs on all laptops and production hosts, reconciled monthly against MDM and cloud inventory.', 14, ctl('EP-01')),
    'CC7.1': row(A, 25, 2, 'Scanner; posture scanner', 'Hosts, containers and dependencies are scanned monthly against remediation SLAs; configuration drift is reviewed monthly.', 10, ctl('VU-01', 'TC-01')),
    'CC7.2': row(G, 15, 0, 'SIEM; MSP SOC', 'Logs are centralised with healthy sources. The weekly alert triage sign-off was done for only 24 of 26 weeks, with the gaps in holiday weeks.', 15, ctl('MON-05', 'MON-06')),
    'CC7.3': row(A, 45, 0, 'Incident tracker', 'Escalated events are logged, severity-classified under the IR plan and tracked to disposition. All 11 in the period were complete.', 18, ctl('IR-01')),
    'CC7.4': row(A, 70, 0, 'IR plan; incident tracker', 'Incidents follow the IR plan with defined roles. The yearly tabletop included contracts (Nancy Huff) and the MSP SOC.', 70, ctl('IR-01', 'IR-02')),
    'CC7.5': row(A, 70, 0, 'Post-incident reviews', 'Both Sev2 incidents had blameless reviews that confirmed recovery and closed their follow-ups. The tabletop tested restoration decisions.', 55, ctl('IR-03', 'IR-02')),
    'CC8.1': row(P, 20, 2, 'Source control; CI pipeline', 'All 410 production merges needed an independent approval and passing CI. One of three break-glass hotfixes has no retro-approval.', 20, ctl('CH-01', 'CH-02')),
    'CC9.1': row(A, 80, 1, 'BCP; DR runbook; cyber insurance', 'The BCP covers key-person cover, alternate vendors and cyber insurance, and is reviewed yearly. The annual DR failover met the 4-hour RTO.', 80, ctl('BC-01', 'DR-01')),
    'CC9.2': row(P, 30, 0, 'Vendor register; SOC report reviews', 'New data-handling vendors are reviewed before contract, and critical vendor SOC reports are reviewed yearly. The payment processor bridge letter is overdue.', 30, ctl('VM-01', 'VM-02', 'VM-03')),
    'A1.1': row(A, 35, 2, 'Monitoring dashboards; synthetic monitoring', 'Capacity is reviewed monthly against forecast, and uptime is reported monthly against the 99.9% SLA. The lowest month was 99.93%.', 8, ctl('CP-01', 'CP-02')),
    'A1.2': row(A, 80, 2, 'Backup console; multi-region deployment', 'Daily immutable backups go to a separate account and failures page on-call. The yearly regional failover is tested, and the cloud provider\'s controls are covered by its SOC report.', null, ctl('BK-01', 'DR-01', 'VM-02')),
    'A1.3': row(P, 20, 2, 'Backup console; DR runbook', 'The Q1 restore test and annual failover are documented. No restore test was run in Q2, repeating a first-period exception.', 80, ctl('BK-02', 'DR-01')),
    'C1.1': row(N, null, 0, '', '', null, ctl('CF-01')),
    'C1.2': row(N, null, 2, '', '', null, ctl('CF-02')),
  },
  findings: [
    {definition: 'CC6.3', title: 'Contractor production access removed 6 business days after termination', severity: 'high', description: 'A contractor\'s production database account stayed active 6 business days after termination, outside the one-business-day standard. This repeats a first-period exception.', action: 'Add non-SSO production accounts to automated deprovisioning and review the access log for the exposure window', assignee: 2, due_in: -5, age: 40},
    {definition: 'CC7.2', title: 'Weekly alert triage review missed for two weeks', severity: 'medium', description: 'No weekly triage sign-off exists for two holiday weeks, so there is no evidence the alert queue was reviewed.', action: 'Assign a named backup reviewer with MSP SOC and retro-review the two missed weeks', assignee: 0, due_in: 20, age: 25},
    {definition: 'A1.3', title: 'Quarterly restore test not performed in Q2', severity: 'medium', description: 'No backup restore test was run in Q2. The first period had the same exception.', action: 'Run and document the missed restore test and schedule recurring calendar holds with a backup owner', assignee: 2, due_in: 30, age: 60},
    {definition: 'CC9.2', title: 'Payment processor bridge letter overdue', severity: 'low', description: 'The payment processor\'s SOC report period ended more than 3 months before our period end, and the bridge letter requested for the gap has not arrived.', action: 'Escalate the bridge letter request through the account manager and record the interim review', assignee: 0, due_in: -10, age: 45},
    {definition: 'CC8.1', title: 'Emergency change missing retro-approval', severity: 'medium', description: 'One of three break-glass hotfixes merged at day -44 was never retro-approved by the engineering lead.', action: 'Obtain documented retro-approval and add an automated reminder for break-glass merges', assignee: 2, due_in: 14, age: 35},
    {definition: 'CC6.3', title: 'Prior period: leaver access removed late', severity: 'high', description: 'In the first Type 2 period, one leaver kept code repository access 9 days after termination. Remediated by adding repository access to the offboarding checklist.', action: 'Add code repository to offboarding checklist and validate on next leavers', assignee: 2, due_in: -110, age: 200, closed_ago: 85},
    {definition: 'CC8.1', title: 'Prior period: 2 of 40 sampled changes lacked approval', severity: 'medium', description: 'Two of 40 sampled production changes in the first Type 2 period were merged without an independent approval. Branch protection now enforces reviewer approval.', action: 'Enforce branch protection requiring an independent approval on main', assignee: 2, due_in: -100, age: 190, closed_ago: 75},
    {definition: 'A1.3', title: 'Prior period: quarterly restore test missed', severity: 'medium', description: 'One quarterly restore test was missed in the first Type 2 period. A make-up test was run and documented.', action: 'Perform make-up restore test and document results', assignee: 2, due_in: -95, age: 185, closed_ago: 62},
  ],
  review_findings: [
    {title: 'Access review found two dormant service accounts with production write access', action: 'Remove dormant service accounts and add service accounts to the quarterly access review scope'},
    {title: 'Vulnerability exceptions accepted by engineering without GRC sign-off', action: 'Route vulnerability SLA exceptions through a documented risk acceptance approved by Dale Doback'},
    {title: 'Collaboration suite SOC report review did not map complementary user entity controls', action: 'Map collaboration suite CUECs to Prestige controls and record owners'},
    {title: 'IR tabletop showed customer notification contacts out of date', action: 'Update customer and insurer notification contacts in the IR plan and confirm with contracts'},
  ],
  risks: [
    {title: 'Customer media or contracts exposed through misconfigured cloud storage', description: 'A storage bucket or signed-URL policy misconfiguration could expose licensed media or customer contract files publicly.', category: 'cybersecurity', likelihood: 2, impact: 5, status: 'in_progress', treatment: 'mitigate', plan: 'Enforce account-level public access blocks and add a storage policy check to the CI pipeline.', owner: 2, reviewed_ago: 30, next_in: 60},
    {title: 'Key-person dependency on Brennan Huff for production access', description: 'Brennan Huff holds most production administration knowledge; his absence would slow incident response and emergency change approval.', category: 'operational', likelihood: 3, impact: 4, status: 'in_progress', treatment: 'mitigate', plan: 'Cross-train a second senior engineer, document runbooks and grant a vaulted secondary admin role.', owner: 1, reviewed_ago: 45, next_in: 45},
    {title: 'Cloud region outage breaches the 99.9% availability SLA', description: 'A full primary-region outage could exceed the monthly downtime allowance and trigger SLA credits.', category: 'availability', likelihood: 2, impact: 4, status: 'assessed', treatment: 'mitigate', plan: 'Maintain warm standby in a secondary region and keep the annual failover test within RTO.', owner: 2, reviewed_ago: 80, next_in: 10},
    {title: 'Licensing rights metadata corrupted or altered', description: 'Incorrect territory, term or rights metadata could lead customers to use media outside licensed terms and produce wrong royalty reports.', category: 'operational', likelihood: 3, impact: 3, status: 'assessed', treatment: 'mitigate', plan: 'Add change audit trails and nightly integrity checks on the rights metadata store.', owner: 0, reviewed_ago: 60, next_in: 30},
    {title: 'Dependency on a single third-party payment processor', description: 'An outage or compromise at the payment processor would interrupt license purchases and card-based renewals.', category: 'vendor', likelihood: 2, impact: 3, status: 'accepted', treatment: 'accept', plan: 'Monitor processor status and SOC reporting; invoice-based purchasing remains available as a manual fallback.', owner: 1, reviewed_ago: 60, next_in: 90,
      acceptance: {rationale: 'A second processor costs more to integrate than the modest exposure warrants, given invoice billing as fallback. Time-limited acceptance approved by Robert Doback and recorded by the vCISO.', ago: 60, expires_in: 120}},
    {title: 'Phishing leads to workforce credential theft', description: 'A successful phishing attack against staff with production or customer data access could lead to account takeover.', category: 'cybersecurity', likelihood: 3, impact: 4, status: 'in_progress', treatment: 'mitigate', plan: 'Complete phishing-resistant MFA rollout for all staff and run quarterly phishing simulations.', owner: 0, reviewed_ago: 20, next_in: 70},
    {title: 'Legacy media-asset backup bucket unencrypted', description: 'A pre-program storage bucket held unencrypted legacy media backups outside the backup platform.', category: 'cybersecurity', likelihood: 1, impact: 4, status: 'closed', treatment: 'mitigate', plan: 'Migrate to encrypted immutable storage and delete legacy bucket.', owner: 2, reviewed_ago: 100, next_in: null,
      closure: {ago: 100, reason: 'remediated', rationale: 'Data migrated to encrypted backup storage, legacy bucket deleted and posture scan confirmed removal.'}},
  ],
  vendors: [
    {name: 'Stratus Peak Cloud (fictional)', services: 'Public cloud infrastructure hosting the licensing platform; carved-out subservice organization', criticality: 'critical', data_types: ['Customer Data', 'Confidential', 'Source Code / IP'], owner: 2, last_review_ago: 75, next_review_in: 290, renewal_in: 240,
      assurance: {type: 'SOC 2', received_ago: 75, refresh_in: 290}, notes: 'Fictional provider. SOC 2 Type 2 reviewed; complementary user entity controls mapped to Prestige controls.'},
    {name: 'Ledgerline Payments (fictional)', services: 'Card payment processing for license purchases and renewals', criticality: 'high', data_types: ['Financial', 'PII'], owner: 1, last_review_ago: 200, next_review_in: 165, renewal_in: 70,
      assurance: {type: 'SOC 2', received_ago: 290, refresh_in: -14}, notes: 'Fictional provider. SOC report period ended more than 3 months before our period end; the bridge letter requested for the gap is overdue (see CC9.2 finding).'},
    {name: 'Bluefin Workspace (fictional)', services: 'Email, documents and collaboration suite', criticality: 'high', data_types: ['Confidential', 'Customer Data', 'Employee Data'], owner: 0, last_review_ago: 150, next_review_in: 215, renewal_in: 160,
      assurance: {type: 'SOC 2', received_ago: 340, refresh_in: 22}, notes: 'Fictional provider. Bridge letter on file; new SOC report due within 30 days.'},
    {name: 'Verity Screening Services (fictional)', services: 'Pre-employment background checks', criticality: 'medium', data_types: ['PII', 'Employee Data'], owner: 1, last_review_ago: 150, next_review_in: 215, renewal_in: 120,
      assurance: {type: 'Security Questionnaire', received_ago: 150, refresh_in: 215}, notes: 'Fictional provider. Managed day to day by HR (Alice Huff); questionnaire reviewed by the GRC manager.'},
  ],
};
export default prestige;
