// Generated Review mappings alone are not client-recorded supporting information.
export const isoEstablishmentInformationRecorded=row=>['implementation','notes'].some(k=>typeof row[k]==='string'&&!!row[k].trim())||!!row.related_links?.some(link=>link.kind!=='reviews');

export const ISO_INTRODUCTIONS={
  soa:'The Statement of Applicability (SoA) records which security controls your organization needs, why they are necessary, and whether they are implemented. ISO/IEC 27001 requires this document as part of information security risk treatment, including justification for excluding any Annex A controls. Use this section to document and maintain those decisions as your organization’s risks, obligations, and operations change.',
  isms_clause:'Clauses 4–10 define how your organization establishes, operates, evaluates, and improves its information security management system (ISMS). They cover areas such as leadership, risk management, resources, internal audit, and continual improvement. These requirements apply to organizations claiming conformity with ISO/IEC 27001. Use this section to assess how your organization meets them and identify gaps.',
  annex_control:'Annex A provides a reference set of security controls covering organizational, people, physical, and technological measures. Your organization must consider this reference set when determining the controls it needs; not every control automatically applies. The Statement of Applicability records those decisions. Use this section to assess how applicable controls are implemented, review supporting evidence, and track gaps.',
  audit:'Internal audit evaluates whether your ISMS meets ISO/IEC 27001 requirements and your organization’s own requirements, and whether it is effectively implemented and maintained. ISO/IEC 27001 requires internal audits at planned intervals, with auditor objectivity and impartiality. Routine reviews and action tracking can provide useful evidence, but do not automatically constitute an internal audit. Use this section to plan audit work, document evidence and conclusions, and track necessary follow-up.'
};
